### ISSUE TITLE
11주차 과제: Enum

### ISSUE THREAD

**Issue by whiteship** [whiteship/live-study#11]
# 목표
자바의 열거형에 대해 학습하세요.

# 학습할 것 (필수)
* enum 정의하는 방법
* enum이 제공하는 메소드 (values()와 valueOf())
* java.lang.Enum
* EnumSet

# 마감일시
2021년 1월 30일 토요일 오후 1시까지.

**Comment by nimkoes** [comment]
11주차 과제 입니다.
https://blog.naver.com/hsm622/222218251749

**Comment by awesomeo184** [comment]
11주차 과제 제출합니다.
https://wisdom-and-record.tistory.com/52

**Comment by asqwklop12** [comment]
빠르게 재출합니다;; 
https://b-programmer.tistory.com/262

**Comment by gowoonsori** [comment]
11주차 제출합니다

**Comment by sujl95** [comment]
11주차 과제 입니다
https://sujl95.tistory.com/66

**Comment by ssonsh** [comment]
11주차 과제입니다. :)
끝을향해 달려가고 있네요!! 
https://www.notion.so/Enum-6ffa87530c424d8ab7a1b585bfb26fa2

**Comment by rlatmd0829** [comment]
https://wookcode.tistory.com/23?category=979588
11주차 과제제출하겠습니다!

**Comment by Gomding** [comment]
11주차 과제 제출합니다! 항상 감사합니다 :)
스터디를 진행하면서 많은분들께 배우고있습니다.
https://parkadd.tistory.com/50

**Comment by mongzza** [comment]
[11주차 과제](https://github.com/mongzza/java-study/blob/main/study/11%EC%A3%BC%EC%B0%A8.md) 제출합니다 감사합니다~

**Comment by tbnsok40** [comment]
한번만 더 빠지면 탈락입니다 정신차리고 하겠습니다!
좋은 기회주셔서 늘 감사드립니다 선장님
https://junior-datalist.tistory.com/61?category=897295

**Comment by rkdals213** [comment]
11주차 과제입니다.

https://www.notion.so/ENUM-831ad8624e4c4aa88030320444aa0543

**Comment by etff** [comment]
11주차 과제 제출합니다.
https://itcoin.tistory.com/507

**Comment by bingbingpa** [comment]
11주차 과제 제출합니다.
https://bingbingpa.github.io/java/whiteship-live-study-week11

**Comment by Chohongjae** [comment]
https://chohongjae.github.io/livestudy/live-study-week11/
11주차 과제입니다.

**Comment by SeungWoo-Oh** [comment]
11주차 과제입니다.
[https://blog.naver.com/swoh1227/222219695440](https://blog.naver.com/swoh1227/222219695440)

**Comment by thisisyoungbin** [comment]
https://young-bin.tistory.com/77
11주차 과제입니다! :)

**Comment by d-h-k** [comment]
https://www.notion.so/11-0c9d3b0449874250a03e1a4f88124baa

11주차 과제입니다!

**Comment by salmon2** [comment]
https://salmon2.github.io/java/2021/01/26/java-week11/
11주차 과제입니다.

**Comment by kjw217** [comment]
11주차 과제입니다.
https://github.com/kjw217/whiteship-live-study/blob/master/11th-week/11th-week.md

**Comment by yangseungin** [comment]
11주차 과제입니다.
https://giantdwarf.tistory.com/52

**Comment by hojunnnnn** [comment]
11주차 과제입니다.
https://dev-coco.tistory.com/22
감사합니다.

**Comment by kwj1270** [comment]
11주차 과제입니다.      
[kwj1270 블로그](https://velog.io/@kwj1270/Enum)

**Comment by lee-maru** [comment]
[11 주차 입니다. !!](https://catch-me-java.tistory.com/48?category=438116)

**Comment by Ahnyezi** [comment]
11주차 과제 제출합니다! 
- [과제 : 자바의 열거형](https://ahnyezi.github.io/java/javastudy-11-enum/)

**Comment by SJParkkk** [comment]
11주차 과제 제출합니다.
https://sjparkk.tistory.com/14

**Comment by DevelopJKong** [comment]
11주차 과제 입니다 감사합니다 :)
https://blog.naver.com/tbaram10/222218997822

**Comment by hyeonic** [comment]
11주차 과제입니다!
https://hyeonic.tistory.com/75

**Comment by 9m1i9n1** [comment]
11주차 과제입니다. 감사합니다~
[11주차 과제](https://github.com/9m1i9n1/TIL_Today-I-Learned/blob/master/05_Java/03_liveStudy/11_Enum.md)

**Comment by sungpillhong** [comment]
https://github.com/sungpillhong/whiteshipstudy/blob/master/11%EC%A3%BC%EC%B0%A8.md

11주차 과제 제출합니다. 이제 4주차 남았는데 다같이 조금만 더 힘내요 !!

**Comment by dongyeon94** [comment]
https://dblog94.tistory.com/entry/Java-Study-11%EC%9D%BC%EC%B0%A8-Enum

11주차 과제입니다.
천천히 조금씩 더 수정해 보겠습니다. ㅠ

**Comment by ksundong** [comment]
11주차 과제 제출합니다!
https://velog.io/@dion/백기선님-온라인-스터디-11주차-Enum

**Comment by Yo0oN** [comment]
11주차 과제 제출합니다.
[11주차 과제](https://github.com/Yo0oN/Tech-Study/blob/master/posts/Java/011.Enum.md)

**Comment by LeeJeongSeok** [comment]
11주차 과제 제출합니다.
- https://velog.io/@ljs0429777/11주차-과제-Enum

**Comment by parksil0** [comment]
11주차 과제 제출합니다. 감사합니다!
https://github.com/parksil0/live-study/blob/master/11th_week.md

**Comment by KJJ924** [comment]
11주차 과제
https://k3068.tistory.com/55

**Comment by Yadon079** [comment]
11주차 과제 제출합니다 :3
https://yadon079.github.io/2021/java%20study%20halle/week-11

**Comment by youngsunshin94** [comment]
11주차 과제 제출합니다.
https://shinysblog.tistory.com/29

**Comment by Lob-dev** [comment]
11주차 과제 제출합니다..!

https://lob-dev.tistory.com/entry/Live-StudyWeek-11-Enum

**Comment by minikuma** [comment]
11주차 과제 제출합니다. 부족한 내용들은 보완해 나가겠습니다. : )
https://www.notion.so/11-Enum-ccbba2bf2b7746ed8a12d2dee09aa833

**Comment by good-influence** [comment]
11주차 과제 제출합니다.

https://www.notion.so/Enum-8f8c0865b492438193f43e720d9f416e

감사합니다.

**Comment by ByungJun25** [comment]
11주차 과제 제출합니다.
https://github.com/ByungJun25/study/tree/main/java/whiteship-study/11week

감사합니다. 👍

**Comment by monkeyDugi** [comment]
https://www.notion.so/11-Enum-21293130df514969870e62828b31d3d7

**Comment by sejongdeveloper** [comment]
11주차 과제 제출합니다.
https://blog.naver.com/sejonghumble/222223602268

**Comment by JadenKim940105** [comment]
11주차 과제입니다 :) 
https://velog.io/@jaden_94/11%EC%A3%BC%EC%B0%A8-%ED%95%AD%ED%95%B4%EC%9D%BC%EC%A7%80-Enum

**Comment by ZhenxiKim** [comment]
11주차 과제 제출합니다.
https://zhenxikim.tistory.com/29?category=906162

**Comment by pka0220z** [comment]
https://out-of-memory.tistory.com/17

이번주는 스스로가 생각해도 너무 미약합니다..
조금 더 공부 후 추후 보완하도록 하겠습니다..

**Comment by SooJungDev** [comment]
[11주차 과제](https://github.com/SooJungDev/TIL/blob/master/Java/live-study/11%EC%A3%BC%EC%B0%A8%EA%B3%BC%EC%A0%9C.md) 제출합니다. 감사합니다!

**Comment by Youngerjesus** [comment]
11주차 과제 제출합니다

https://velog.io/@youngerjesus/%EC%9E%90%EB%B0%94-Enum

**Comment by jymaeng95** [comment]
11주차 과제 제출합니다.
https://velog.io/@zayson/백기선님과-함께하는-Live-Study-11주차-Enum

**Comment by morethanmin** [comment]
과제 제출하겠습니다
https://moredevmin.tistory.com/21

**Comment by plzprayme** [comment]
[과제 제출합니다](https://velog.io/@prayme/whiteship-11%EC%A3%BC%EC%B0%A8-Enum)

**Comment by kingsubin** [comment]
https://kingsubin.tistory.com/344

**Comment by haemin-jeong** [comment]
11주차 과제 제출합니다. 감사합니다:)
https://developer-hm.tistory.com/33

**Comment by Sungjun-HQ** [comment]
https://whereishq.blogspot.com/2021/01/11-enum.html

감사합니다~

**Comment by limyeonsoo** [comment]
https://www.notion.so/11-Enum-49e855aee2d44281a176bfd511630c6e
11주차 과제입니다.
감사합니다

**Comment by jjone36** [comment]
11주자 제출합니다. 부족한 부분은 계속 추가하겠습니다~
https://github.com/jjone36/self-study/blob/main/java_live_study/week11.md

**Comment by Junhan0037** [comment]
11주차 과제 제출합니다.
https://www.notion.so/11-Enum-e573f79faf364c58aefcb3dbe0b07dde

**Comment by haemanlee** [comment]
11주차 과제 제출합니다.

https://haemanlee.tistory.com/10

**Comment by KyungJae-Jang** [comment]
11주차 과제 제출합니다.
감사합니다!
https://www.notion.so/11-Enum-8ea112a3e89249d788cc1706878cff1d

**Comment by gtpe** [comment]
11주차 과제입니다! 감사합니다(__)
https://github.com/gtpe/java-study/blob/master/w11.md

**Comment by LeeGiCheol** [comment]
11주차 과제입니다.
https://leegicheol.github.io/whiteship-live-study/whiteship-live-study-11-enum/

enumset은 비트연산자를 사용할 일이 적어서 그런지 와닿지가 않네요...
이번 스터디 끝나고 보완해보겠습니다!

감사합니다!!

**Comment by hoi-hoon** [comment]
11주차 과제 제출합니다!
https://hoi-hoon.github.io/study/live-study-11/

**Comment by rockintuna** [comment]
안녕하세요. 11주차 과제 제출합니다!
https://rockintuna.tistory.com/93

**Comment by gcha-kim** [comment]
안녕하세요 11주차 과제 제출합니다!
https://www.notion.so/gcha/11-Week-Enum-879f86473c634c1da62f094371a364e7

**Comment by k8440009** [comment]
11주차 과제 제출합니다.
https://www.notion.so/11-Enum-9c27691f2f804a9baa2ed1dd212c6776

**Comment by kyu9** [comment]
11주차 과제입니다! 
https://github.com/kyu9/WS_study/blob/master/week11.md
이번주는 꼭 라이브 참여해서 열심히 더 배워보도록 하겠습니다!!

**Comment by mia0406** [comment]
11주차 과제 제출합니다!
https://mia0406.github.io/programming/2021/01/29/11%EC%A3%BC%EC%B0%A8-%EA%B3%BC%EC%A0%9C-Enum.html

**Comment by garlickim** [comment]
11주차 과제 제출합니다.
[https://github.com/garlickim/whiteship-live-java-study/week11](https://github.com/garlickim/whiteship-live-java-study/blob/main/%5Bweek11%5D%20Enum.md)

**Comment by joey3116** [comment]
11주차 과제입니다.
미약하지만 , 
저번주터 시작하여 꾸준히 해보겠습니다.
[11주차 과제](https://github.com/joey3116/live-study/blob/master/11week_assignment.md)

**Comment by 2yeseul** [comment]
11주차 과제 제출합니다
https://seulog.netlify.app/Java/Enum/

**Comment by Resilient923** [comment]
11주차 과제 제출합니다!
https://resilient-923.tistory.com/122

**Comment by jameshan521** [comment]
11주차 과제 제출합니다!
https://imdigging.tistory.com/8

**Comment by pej4303** [comment]
11주차 과제 제출합니다~
https://pej4303.tistory.com/61

**Comment by dacapolife87** [comment]
https://github.com/dacapolife87/javaStudy/blob/main/study/week11/Week11_enum.md
11주차 과제제출 합니다.

**Comment by Jangilkyu** [comment]
11주차 과제 제출합니다.
https://github.com/Jangilkyu/Java_Study/tree/main/Weeks11

**Comment by doyoung0205** [comment]
11주차 과제 제출합니다.
https://doyoung.tistory.com/manage/posts/

**Comment by numuduwer** [comment]
11주차 과제 제출합니다!
https://www.notion.so/11-Enum-6a7dcb3dbffe495f8984e1c08c3a0045

**Comment by MoonHKLee** [comment]
https://leemoono.tistory.com/27

**Comment by keunyop** [comment]
https://github.com/keunyop/java-study-with-whiteship/blob/main/live-study/week11.md

감사합니다.

**Comment by tocgic** [comment]
11주차 과제 제출드립니다.
https://github.com/tocgic/study-java-basic/blob/main/week11.md
감사합니다.

**Comment by ShimSeoungChul** [comment]
11주차 과제 제출합니다!
https://scshim.tistory.com/253
감사합니다.

**Comment by fpdjsns** [comment]
11주차 과제 제출합니다.
https://withhamit.tistory.com/526
감사합니다.

**Comment by devShLee7017** [comment]
11주차 과제 제출합니다.
https://velog.io/@bluesky7017/Enum

**Comment by hongminpark** [comment]
11주차 과제 제출합니다. https://hongminpark.github.io/2021-01-30/studyhalle11

**Comment by damho1104** [comment]
11주차 스터디 자료 공유합니다.
https://www.notion.so/damho1104/11-Enum-04ffc85a46994951a5966f6b4c7af526
이번주는 바빠서 늦게 업로드했네요....

**Comment by ChoiGiSung** [comment]
항상 감사드립니다.
https://github.com/ChoiGiSung/JavaStudy/blob/main/11%EC%A3%BC%EC%B0%A8.md

**Comment by parker1609** [comment]
안녕하세요!
11 주차 과제 제출합니다!
[11 주차 과제 링크](https://www.notion.so/11-Enum-7e6b23f06e26475db67e9c3f0f941e3d)

감사합니다!

**Comment by yeGenieee** [comment]
11주차 과제 제출합니다 ~ 
https://github.com/yeGenieee/java-live-study/blob/main/%5B11%5DJava%20Live%20Study.md

**Comment by abcdsds** [comment]
11주차 과제 제출합니다
https://www.notion.so/11-Enum-d4776efeab674cff8ed4cf67329c1c8d

**Comment by honux77** [comment]
[11주차 스터디  열거형](https://velog.io/@honux/%EB%B0%B1%EA%B8%B0%EC%84%A0-%EC%9E%90%EB%B0%94-%EB%9D%BC%EC%9D%B4%EB%B8%8C-%EC%8A%A4%ED%84%B0%EB%94%94-11-%EC%97%B4%EA%B1%B0%ED%98%95)
모두 화이팅!

**Comment by yhh1056** [comment]
11주차 과제 제출합니다.
https://www.notion.so/aeno/Enum-8bf1bafc23be43e3a70d4e9261cf1d5f

**Comment by ysmiler** [comment]
[11주차](https://ysmiler.github.io/study/java/live-study/week11/)

과제 제출합니다. 감사합니다!! 공부 더 하겠습니다ㅠㅠ

**Comment by redbean88** [comment]
https://github.com/redbean88/redbean88.github.io/blob/master/_posts/2021-01-29-whiteship-study-11week.md

11주차 입니다. 2주안 이직때문에 진행을 못하고 있네요. 추가 보충하겠습니다. 죄송합니다 ㅠㅠ

**Comment by chulphan** [comment]
안녕하세요

11주차 과제 제출합니다

감사합니다
https://chulphan.tistory.com/14

**Comment by 1031nice** [comment]
https://github.com/1031nice/JavaStudy/blob/master/live-study/week11.md

감사합니다!

**Comment by LeeWoooo** [comment]
11주차 과제입니다 감사합니다!
https://github.com/LeeWoooo/Java_LiveStudy/tree/master/week11

**Comment by yky03** [comment]
11주차 과제입니다. 감사합니다.
https://github.com/yky03/java-study-issues/blob/main/week11-enum.md

**Comment by resister12** [comment]
11주차 과제입니다.
https://www.notion.so/11-c9883c69c0e74c2ea92fc3f640cd8e28

**Comment by infoqoch** [comment]
11주차 과제입니다! 
https://velog.io/@infoqoch/enum%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC

**Comment by dmstjd1024** [comment]
11주차 과제입니다.
https://dmstjd1024.github.io/2021/01/28/live-study11.html

**Comment by giyeon95** [comment]
11주차 과제 제출합니다.
https://giyeon95.github.io/whiteship/whiteship_study_week11/

**Comment by Jason-time** [comment]
11주차 과제입니다.
https://github.com/Jason-time/java_study_with_whiteship/blob/main/mds/week11.md

**Comment by ddings73** [comment]
11주차 과제입니다.
https://ddings73.github.io/Study_Category/Java/Live_study/week11.html

**Comment by sangwoobae** [comment]
늦었지만 11주차 과제 입니다.
EnumSet은 자세히 몰랐는데 이번 기회에 조금 더 상세하게 알게 되었고 따로 말씀은 안하셨지만 EnumMap에 대해서도 잠시 알아보게 되었습니다.
항상 감사 드립니다!

https://blog.baesangwoo.dev/posts/java-livestudy-11week/

**Comment by gintire** [comment]
11주차 과제입니다~
https://gintrie.tistory.com/72

**Comment by roeniss** [comment]
11주차 제출합니다
https://velog.io/@roeniss/자바-기초지식-정리

**Comment by kgc0120** [comment]
11주차 제출합니다!
https://gyucheolk.tistory.com/17
감사합니다~

**Comment by highright96** [comment]
11주차 제출합니다~
https://github.com/highright96/java-study/blob/main/live-study/week11/week11.md

**Comment by WonYong-Jang** [comment]
11주차 과제 제출합니다.   
[https://wonyong-jang.github.io/java/2021/01/29/Java-enum.html](https://wonyong-jang.github.io/java/2021/01/29/Java-enum.html)

**Comment by oktopman** [comment]
11주차 과제 제출합니다.
https://github.com/oktopman/java-live-study/blob/main/assignment/week11.md

**Comment by JungHyeokMoon** [comment]
https://www.notion.so/11-4ed2c201096641a98fcc4fa6a80d5f5e
11주차 과제입니다.

**Comment by QurieMoon** [comment]
안녕하세요? 과제 제출이 늦었습니다ㅠㅠ
11주차 과제 제출합니다!
https://github.com/QurieMoon/TIL/blob/main/whiteship-live-study/2021-01-30-whiteship-week11.md#enum%EC%9D%B4-%EC%A0%9C%EA%B3%B5%ED%95%98%EB%8A%94-%EB%A9%94%EC%86%8C%EB%93%9C-values()%EC%99%80-valueOf()

**Comment by ahyz0569** [comment]
https://github.com/ahyz0569/Study/blob/main/Java-study/week_011.md
11주차 과제 제출합니다!

**Comment by kongduboo** [comment]
[11주차 과제: Enum](https://github.com/kongduboo/whiteship-java-study/blob/main/week11.md)
늦었지만 제출합니다. 감사합니다.

**Comment by reumongshop** [comment]
11주차 과제 제출합니다 :)
https://blog.naver.com/reumongshop/222227795214

**Comment by Azderica** [comment]
11주차 과제제출합니다.
https://azderica.github.io/11-java-enum/

**Comment by geneaky** [comment]
11주차 과제 제출합니다 :) 
https://www.notion.so/WEEK-11-1ed68fbe6cea4bec9cf9dc7fbade86e5

**Comment by KwangJongJeon** [comment]
11주차 과제 제출합니다.
https://kj97.tistory.com/16

**Comment by jongyeans** [comment]
11주차 과제 제출합니다.
https://morebetterworld.tistory.com/13

**Comment by rowanlee92** [comment]
11주차 과제 제출합니다!
https://watrv41.gitbook.io/devbook/java/java-live-study/11_week

**Comment by jongnan** [comment]
11주 차 과제 제출합니다.
 * [Enum](https://github.com/jongnan/Java_Study_With_Whiteship/blob/master/week11/week11.md)

**Comment by sinchang1** [comment]
11주차 과제입니다-
https://www.notion.so/Week_11-Baik-s-JAVA_STUDY-e4fff879ec604574aeb090bdc6eeb32b

**Comment by Park-SooYeon** [comment]
11주차 과제 제출합니다.
https://github.com/Park-SooYeon/today-I-learned/blob/master/live-study/enum.md

**Comment by soongjamm** [comment]
11주차 제출합니다.
https://github.com/soongjamm/java-study/tree/master/src/live_study/src/main/java/week11

**Comment by sskim91** [comment]
11주차 제출합니다.
https://amagrammer91.tistory.com/58

**Comment by castleCircle** [comment]
https://castleone.tistory.com/13 11주차 제출합니다.

**Comment by chaejunlee** [comment]
11주차 과제 제출합니다!
https://www.notion.so/chaejunlee/11-Enum-cbbaa0f272f6475a963a4a8b66962802

**Comment by jikimee64** [comment]
https://dncjf64.tistory.com/287
11주차 과제 제출합니다!!

**Comment by jeeneee** [comment]
11주차 과제 제출합니다
https://jeeneee.dev/java-live-study/week11-enum/

**Comment by cmg1411** [comment]
[11주차 과제 제출합니다 !!](https://alkhwa-113.tistory.com/entry/11%EC%A3%BC%EC%B0%A8-enum)

**Comment by loosie** [comment]
https://loosie.tistory.com/133

11주차 제출합니다!

**Comment by myBabyGrand** [comment]
[11주차 Enum](https://github.com/myBabyGrand/study_JAVA_whiteship_live-study/blob/main/md_doc/11.Enum.md
제출합니다!

**Comment by lkimilhol** [comment]
과제 제출합니다.

https://github.com/lkimilhol/whiteship/blob/master/study/week11.md

**Comment by Ohzzi** [comment]
11주차 과제 제출합니다.
https://velog.io/@ohzzi/Live-Study-11

**Comment by ventulus95** [comment]
11주차 과제 제출입니다
https://www.notion.so/ventulus95/Enum-ea8964ee6d454fde8562732cc4a65cfe

**Comment by ows3090** [comment]
11주차 과제 제출합니다.
https://math-coding.tistory.com/179

**Comment by HyangKeunChoi** [comment]
11주차 Enum 늦은 과제 제출입니다.! ⏰

https://geunyang93.tistory.com/50

**Comment by haeinoh** [comment]
11주차 과제 제출합니다. 감사합니다.

https://void2017.tistory.com/208

**Comment by conyconydev** [comment]
11주차 제출합니다. 
https://roeldowney.tistory.com/494

**Comment by rshak8912** [comment]
11주차 과제 제출합니다.
[11주차 과제](https://java-boy.tistory.com/113)

**Comment by loop-study** [comment]
11주차 제출합니다
https://loopstudy.tistory.com/19

**Comment by devHTak** [comment]
11주차 과제 제출합니다.

https://devhtak.github.io/java%20study/2021/02/03/StudyHalle_Week11.html

**Comment by heewonham** [comment]
11주차 과제 제출합니다 ^,^

https://blog.naver.com/micky6414/222248590976

**Comment by azurealstn** [comment]
https://github.com/azurealstn/TIL/blob/main/java/live-study/week-11.md
11주차 따라갑니다.

**Comment by GetMapping** [comment]
11주차 제출합니다!
https://www.notion.so/11-Enum-aeac1cbc509d4d6ea9fd44f7a8e6c840

**Comment by jigmini** [comment]
늦었지만 11주차 과제 제출합니다!
https://blog.naver.com/jigmini/222252252195

**Comment by Hwanse** [comment]
11주차 과제를 제출합니다.

https://velog.io/@khsb2012/java-study-week11

**Comment by UmJaeJeong** [comment]
11주차 과제입니다.
https://blog.naver.com/umjaejeong2/222247924591

**Comment by sophysophysophysophy** [comment]
11주차 과제 제출합니다. 
https://read-write-developer.tistory.com/124

**Comment by shinnyoung** [comment]
11주차 과제 제출합니다!
https://parkbeaver.tistory.com/27

**Comment by daroguzo** [comment]
[https://github.com/daroguzo/JavaLiveStudy/commit/d5acafc8bba45351bce22461f6014c71784ecca0](url)
11주차 과제 제출합니다.

**Comment by delusidiot** [comment]
https://delusidiot.tistory.com/entry/11-%EC%A3%BC%EC%B0%A8-%EA%B3%BC%EC%A0%9C-Enum
11주차 과제 제출합니다.

**Comment by JIN-096** [comment]
11주차 과제 제출합니다!
(과제제출)[https://0x60.tistory.com/23]

**Comment by justinnn980** [comment]
https://justinnn980.tistory.com/manage/posts/

**Comment by jaeeunis** [comment]
과제 제출합니다
https://github.com/jaeeunis/TIL/blob/main/Java/Enum.md

**Comment by s0w0s** [comment]
https://www.notion.so/11-7d738920773b49419a376e097f7e6294
11주차 과제 제출합니다~

**Comment by hhlyn0328** [comment]
11주차 과제입니다!
https://hongkey90.tistory.com/24

**Comment by jiwoo-choi** [comment]
11주차 밀렸던거 채워나가봅니다! 
https://www.notion.so/11-Enum-80086bf71c2f4b22aa55e3fe46d20b0b

**Comment by younwony** [comment]
11주차 과제입니다
https://youn12.tistory.com/34

**Comment by eatnows** [comment]
https://eatnows.tistory.com/91
11주차 과제입니다!

**Comment by youngjinmo** [comment]
11주차 과제 제출합니다!
https://youngjinmo.github.io/2021/03/livestudy-week-11/

**Comment by yskkkkkk** [comment]
11주차 과제 제출하겠습니다! 
https://knowing-today.blogspot.com/2021/01/11-enum.html#more

**Comment by pond1029** [comment]
https://velog.io/@pond1029/enum
늦었습니다.

**Comment by yongtaelim** [comment]
https://jessyt.tistory.com/82
제출합니다!

**Comment by DDOEUN** [comment]
11주차 과제 제출합니다.
https://teamo-oeun.tistory.com/18

**Comment by devvip** [comment]
11주차 과제 제출합니다!

https://velog.io/@eledev/JAVA-STUDYwith-whiteship-11주차-Enum

**Comment by kdh9428** [comment]
11주차 과제 제출합니다.
https://www.notion.so/11-9a25d25f80034b319a7bb406abdef7b0

**Comment by choiyoungkwon12** [comment]
11주차 과제 제출합니다.
https://cyk0825.tistory.com/29

**Comment by tinajeong** [comment]
11주차 제출합니다!
https://velog.io/@maigumi/Enum

**Comment by Taein2** [comment]
11주차 제출입니다!
https://codingrepo.tistory.com/40

**Comment by inhalin** [comment]
11주차 과제 제출합니다.
https://github.com/inhalin/whiteship-live-study/blob/main/week11.md

**Comment by YuSeungmo** [comment]
11주차 과제 제출합니다.
https://github.com/YuSeungmo/java_study/blob/main/study/11%EC%A3%BC%EC%B0%A8.md

**Comment by hanseo0109** [comment]
11주차 과제 제출합니다
https://velog.io/@hanseo0109/step11-Enum

**Comment by cs7998** [comment]
11주차 과제 제출합니다.
https://github.com/cs7998/live-study-java/blob/main/11.Enum.md
