### ISSUE TITLE
12주차 과제: 애노테이션

### ISSUE THREAD

**Issue by whiteship** [whiteship/live-study#12]
# 목표
자바의 애노테이션에 대해 학습하세요.

# 학습할 것 (필수)
* 애노테이션 정의하는 방법
* @Retention
* @Target
* @Documented
* 애노테이션 프로세서

# 마감일시
2021년 2월 6일 토요일 오후 1시까지.

**Comment by asqwklop12** [comment]
https://b-programmer.tistory.com/264 
이번에도 빠르게 제출 합니다.

**Comment by sujl95** [comment]
https://sujl95.tistory.com/67
12주차 과제 입니다

**Comment by gowoonsori** [comment]
12주차 과제 제출합니다!
[https://gowoonsori.site/java/annotation/](https://gowoonsori.site/java/annotation/)

**Comment by nimkoes** [comment]
12주차 과제 입니다.
https://blog.naver.com/hsm622/222226824623

**Comment by monkeyDugi** [comment]
https://www.notion.so/386f4cd47d37448fa0252d3ed22b45b7

**Comment by Gomding** [comment]
12주차 과제입니다.  &#128674;
https://parkadd.tistory.com/54

**Comment by bingbingpa** [comment]
12주차 과제 제출합니다. 
https://bingbingpa.github.io/java/whiteship-live-study-week12

**Comment by ssonsh** [comment]
12주차 과제 제출합니다. : )
https://www.notion.so/37d183f38389426d9700453f00253532

**Comment by rlatmd0829** [comment]
https://wookcode.tistory.com/24?category=979588

**Comment by awesomeo184** [comment]
12주차 과제 제출합니다.
https://wisdom-and-record.tistory.com/54

**Comment by hojunnnnn** [comment]
12주차 과제 제출합니다 ~
https://dev-coco.tistory.com/24

**Comment by youngsunshin94** [comment]
12주차 과제 제출합니다.
https://shinysblog.tistory.com/31

**Comment by KyungJae-Jang** [comment]
12주차 과제 제출합니다!!!
https://www.notion.so/12-95595cad188b45058bfb1ddcf97869c5

**Comment by Yadon079** [comment]
12주차 제출합니다 :3
https://yadon079.github.io/2021/java%20study%20halle/week-12
프로세서 부분은 좀 더 공부해보겠습니다!

**Comment by Lob-dev** [comment]
12주차 과제 제출합니다~~@!

https://lob-dev.tistory.com/entry/Live-StudyWeek-12-Annotation

**Comment by sejongdeveloper** [comment]
12주차 과제 제출합니다.
https://blog.naver.com/sejonghumble/222229467393

**Comment by SeungWoo-Oh** [comment]
12주차 과제 제출합니다.
[https://blog.naver.com/swoh1227/222229853664](https://blog.naver.com/swoh1227/222229853664)

**Comment by hyeonic** [comment]
12주차 과제 제출입니다!
https://hyeonic.tistory.com/88

**Comment by rkdals213** [comment]
12주차 과제입니다.

https://www.notion.so/Annotation-585f4a8b1585485381ef278bc86c80fd

**Comment by Yo0oN** [comment]
12주차 과제입니다.
[12주차 과제](https://github.com/Yo0oN/Tech-Study/blob/master/posts/Java/012.Annotation.md)

**Comment by KJJ924** [comment]
12주차 과제
https://k3068.tistory.com/62

**Comment by Youngerjesus** [comment]
12주차 과제 제출합니다

https://velog.io/@youngerjesus/%EC%9E%90%EB%B0%94-Annotation

**Comment by JadenKim940105** [comment]
12주차 과제입니다 :) 
https://velog.io/@jaden_94/12%EC%A3%BC%EC%B0%A8-%ED%95%AD%ED%95%B4%EC%9D%BC%EC%A7%80-Annotation

**Comment by pej4303** [comment]
12주차 과제입니다~
https://pej4303.tistory.com/62

**Comment by sungpillhong** [comment]
https://github.com/sungpillhong/whiteshipstudy/blob/master/12%EC%A3%BC%EC%B0%A8.md

12주차 과제 제출합니다 !

**Comment by ksundong** [comment]
과제 제출합니다!
https://velog.io/@dion/백기선님-온라인-스터디-12주차-Annotation

**Comment by giyeon95** [comment]
과제 제출합니다
https://giyeon95.github.io/whiteship/whiteship_study_week12

**Comment by dongyeon94** [comment]
12일차 업로드 합니다.

https://dblog94.tistory.com/entry/Java-Study-12%EC%9D%BC%EC%B0%A8-Annotation

스터디 하는 도중  'functional  인터페이스 지시자' 라는 키워드가 있었는데  무슨 의미인지 찾아봐도 잘 안나옵니다. ㅠ
무슨 의미일까요..?

**Comment by Chohongjae** [comment]
https://chohongjae.github.io/livestudy/live-study-week12/
12주차 과제입니다.

**Comment by yangseungin** [comment]
과제 제출합니다.
https://giantdwarf.tistory.com/55

**Comment by ddings73** [comment]
12주차 제출합니다.
https://ddings73.github.io/Study_Category/Java/Live_study/week12.html

**Comment by parksil0** [comment]
12주차 과제 제출합니다. 항상 감사합니다.
https://github.com/parksil0/live-study/blob/master/12th_week.md

**Comment by jongnan** [comment]
12주차 과제 제출합니다.
* [애노테이션](https://github.com/jongnan/Java_Study_With_Whiteship/blob/master/week12/week12.md)

**Comment by LeeJeongSeok** [comment]
12주차 과제 제출합니다.
- https://velog.io/@ljs0429777/12주차-과제-애노테이션

**Comment by ByungJun25** [comment]
12주차 과제 제출합니다.
어노테이션 프로세서에 대해 많이 배웠습니다. 감사합니다.

**Comment by kjw217** [comment]
12주차 과제입니다.
https://github.com/kjw217/whiteship-live-study/blob/master/12th-week/12th-week.md

**Comment by Azderica** [comment]
12주차 과제제출합니다.
https://azderica.github.io/12-java-study

**Comment by Ahnyezi** [comment]
12주차 과제 제출합니다! 감사합니다 :)

- [자바의 어노테이션](https://ahnyezi.github.io/java/javastudy-12-annotation/)

**Comment by kwj1270** [comment]
12주차 과제 제출입니다.   
[kwj1270 블로그](https://velog.io/@kwj1270/%EC%96%B4%EB%85%B8%ED%85%8C%EC%9D%B4%EC%85%98)

**Comment by good-influence** [comment]
12주차 과제 제출합니다 

https://www.notion.so/0b4ef3bf7a134334ba976736f613039e

감사합니다.

**Comment by 9m1i9n1** [comment]
12주차 과제 제출합니다~
[12주차 과제](https://github.com/9m1i9n1/TIL_Today-I-Learned/blob/master/05_Java/03_liveStudy/12_%EC%95%A0%EB%85%B8%ED%85%8C%EC%9D%B4%EC%85%98.md)

**Comment by minikuma** [comment]
12주차 과제 제출합니다. 부족한 부분은 계속 채워 가도록 하겠습니다.
https://www.notion.so/12-a4b39805e8c045729e2167e88088a7f9

**Comment by joey3116** [comment]
12주차 과제 제출합니다.
[12주차 과제](https://github.com/joey3116/live-study/blob/master/12week_assignment.md)

**Comment by reumongshop** [comment]
12주차 과제 제출합니다 :)
https://blog.naver.com/reumongshop/222227799210

**Comment by jymaeng95** [comment]
12주차 과제 제출합니다.
https://velog.io/@zayson/백기선님과-함께하는-Live-Study-12주차-애노테이션

**Comment by fpdjsns** [comment]
https://withhamit.tistory.com/533
12주차 과제 제출합니다.

**Comment by ZhenxiKim** [comment]
https://zhenxikim.tistory.com/30

**Comment by gtpe** [comment]
12주차 과제입니다! 감사합니다(__)
https://github.com/gtpe/java-study/blob/master/w12.md

**Comment by inhalin** [comment]
12주차 과제 제출합니다.
https://github.com/inhalin/whiteship-live-study/blob/main/week12.md

**Comment by limyeonsoo** [comment]
12주차 과제 제출합니다.
이미 있는 애노테이션들을 외워서 사용하는 줄만 알았는데 이번기회에 새로만들어보는 경험도 가질 수 있었어요
감사합니다.
https://www.notion.so/12-Annotation-32058769549c4c21a92af99e81903fb6

**Comment by Junhan0037** [comment]
12주차 과제 제출합니다.
https://www.notion.so/12-9dd1d56429b94ad18e9649a85dfdc0fd

**Comment by jameshan521** [comment]
https://imdigging.tistory.com/9

12주차 과제 제출합니다! 감사합니다~

**Comment by DevelopJKong** [comment]
https://blog.naver.com/tbaram10/222226543878
12주차 과제 제출합니다! 감사합니다!!

**Comment by ChoiGiSung** [comment]
https://github.com/ChoiGiSung/JavaStudy/blob/main/12%EC%A3%BC%EC%B0%A8.md
감사합니다! 많이 배웠습니다.

**Comment by haemin-jeong** [comment]
애노테이션 프로세서 부분이 부족한데... 코드 조작 강의 들으면서 공부하겠습니다. 감사합니다!
https://developer-hm.tistory.com/35

**Comment by etff** [comment]
12주차 과제입니다
https://itcoin.tistory.com/511

**Comment by mongzza** [comment]
[12주차](https://github.com/mongzza/java-study/blob/main/study/12%EC%A3%BC%EC%B0%A8.md) 제출합니다. 감사합니다~

**Comment by lee-maru** [comment]
이번 스터디를 통해,  AST를 직접 조작하는 방법으로 롬복의 getter 와 setter 를 만들어보았습니다. 

[롬복의 @getter, @setter 를 직접 만들어보자])(https://catch-me-java.tistory.com/49)

**Comment by sangwoobae** [comment]
12주차 과제 제출합니다. 감사합니다~
https://blog.baesangwoo.dev/posts/java-livestudy-12week/

**Comment by gcha-kim** [comment]
12주차 과제입니다.
https://www.notion.so/gcha/12-Week-Annotation-907d3054ceb04f7e9da6555195bd811e

**Comment by LeeGiCheol** [comment]
안녕하세요!! 
12주차 과제 제출합니다~
감사합니다!!

https://leegicheol.github.io/whiteship-live-study/whiteship-live-study-12-annotation/

**Comment by LeeWoooo** [comment]
12주체 과제 제출합니다 감사합니다:)
https://github.com/LeeWoooo/Java_LiveStudy/tree/master/week12

**Comment by garlickim** [comment]
12주차 과제 제출합니다. 감사합니다.
[https://github.com/garlickim/whiteship-live-java-study/week12](https://github.com/garlickim/whiteship-live-java-study/blob/main/%5Bweek12%5D%20%EC%96%B4%EB%85%B8%ED%85%8C%EC%9D%B4%EC%85%98.md)

**Comment by sunnynote** [comment]
안녕하세요. [12주차 과제](https://happyday3.tistory.com/82) 제출합니다. 감사합니다!

**Comment by dmstjd1024** [comment]
12주차 과제 제출합니다!
https://dmstjd1024.github.io/2021/02/05/live-study12.html

**Comment by SJParkkk** [comment]
12주차 과제 제출합니다!
https://sjparkk.tistory.com/17

**Comment by Jangilkyu** [comment]
https://github.com/Jangilkyu/Java_Study/tree/main/Weeks12

**Comment by jongyeans** [comment]
질문이 있어 미완성된 과제를 올려보며 스터디 이후 다시 완성하도록 하겠습니다. 
https://morebetterworld.tistory.com/14

# 질문사항 
어노테이션 중에 "@Inherited" 의 용도가 궁금합니다. 
어노테이션은 상속이 불가능한데, 상속받은 자식 클래스에서 해당 어노테이션을 갖고 있는것으로 개념적으로 내용은 이해되었는데 실제 사용하는 경우가 있는지 궁금합니다.

**Comment by numuduwer** [comment]
과제 제출합니다.

**Comment by damho1104** [comment]
이번 스터디 내용 공유합니다.
https://www.notion.so/damho1104/12-4f396f3b5d8844548c224161f78d4aa3
이번주는 너무 바빠서 공부를 깊이 있게 못했네요...ㅜㅜ

**Comment by doyoung0205** [comment]
과제 제출합니다.
https://doyoung.tistory.com/25

**Comment by SooJungDev** [comment]
[12주차 과제](https://github.com/SooJungDev/TIL/blob/master/Java/live-study/12%EC%A3%BC%EC%B0%A8%EA%B3%BC%EC%A0%9C.md) 제출합니다. 감사합니다!

**Comment by yhh1056** [comment]
https://www.notion.so/aeno/e6d2b538bca845939f079865f482d07d
12주차 과제 제출합니다~

**Comment by sinchang1** [comment]
https://www.notion.so/Week_12-Baik-s-JAVA_STUDY-4f07f69af2d34b1aa4f40ccb93e74041
12주차 과제 제출합니다~

**Comment by 1031nice** [comment]
감사합니다.
https://github.com/1031nice/JavaStudy/blob/master/live-study/week12.md

**Comment by honux77** [comment]
[13주차 과제](https://velog.io/@honux/%EB%B0%B1%EA%B8%B0%EC%84%A0-%EC%9E%90%EB%B0%94-%EB%9D%BC%EC%9D%B4%EB%B8%8C-%EC%8A%A4%ED%84%B0%EB%94%94-13-Annotation)

감사합니다!

**Comment by parker1609** [comment]
안녕하세요.
12주차 과제 제출합니다.
[12주차 과제 링크](https://www.notion.so/12-fbcfedb061554ce29e55f218a419e01a)

감사합니다!

**Comment by yeGenieee** [comment]
12주차 과제 제출합니다 !
https://github.com/yeGenieee/java-live-study/blob/main/%5B12%5DJava%20Live%20Study.md

**Comment by redbean88** [comment]
12주차 과제입니다. 
https://redbean88.github.io/study/whiteship-study-12week/

## 질문

어노테이션 프로세서가 꼭 컴파일시와 같은 바이트코드 조작만 말하는건지, 어노테이션을 이용한 서비스 개선도 어노테이션 프로세서라 말할수 있는지 궁금합니다.

**Comment by Sungjun-HQ** [comment]
https://whereishq.blogspot.com/2021/02/12.html

항상 감사합니다.

시간 분배를 잘못했습니다.
앞의 내용이 '애노테이션 프로세서' 구현을 위한 스터디였다는걸 마지막 '애노테이션 프로세서'를 들여다보면서 알았습니다. ㅠㅜ

**Comment by hongminpark** [comment]
12주차 과제 재출합니다 https://hongminpark.github.io/2021-02-06/studyhalle12

**Comment by 2yeseul** [comment]
12주차 과제 제출합니다. https://github.com/2yeseul/TIL/blob/master/Java/Annotation.md

**Comment by ysmiler** [comment]
[12주차](https://ysmiler.github.io/study/java/live-study/week12)

과제 제출합니다. 감사합니다!!

**Comment by chulphan** [comment]
안녕하세요

12주차 과제 제출합니다

감사합니다

https://chulphan.tistory.com/15

**Comment by JeongJin984** [comment]
12주자 과제 제출합니다.
https://github.com/JeongJin984/JeongJin984.github.io/blob/master/_posts/2021-02-26-Java-Annotation.md

**Comment by JJongSue** [comment]
12주차 과제 제출합니다.
https://github.com/JJongSue/javastudy/tree/master/src/main/java/week12

**Comment by hoi-hoon** [comment]
12주차 과제입니다. 감사합니다!
https://hoi-hoon.github.io/study/live-study-12/

**Comment by KilJaeeun** [comment]
https://kils-log-of-develop.tistory.com/540

**Comment by integer87** [comment]
12주차 과제 제출합니다.
https://github.com/integer87/study/blob/master/week12/week12.md

애노테이션 프로세서를 따라서 한번 만들어 봤는데.. 잘 안되더라구요
스터디때 간단한 애노테이션 프로세서를 만들어서 적용한번 해주실 수 있으신가요?

**Comment by plzprayme** [comment]
[과제 제출합니다](https://velog.io/@prayme/whiteship-12%EC%A3%BC%EC%B0%A8-Enum)

**Comment by ahyz0569** [comment]
12주차 과제 제출합니다!
https://github.com/ahyz0569/Study/blob/main/Java-study/week_012.md

**Comment by yky03** [comment]
12주차 과제 제출합니다. 감사합니다.
https://github.com/yky03/java-study-issues/blob/main/week12-annotation.md

**Comment by haemanlee** [comment]
https://haemanlee.tistory.com/11

12주차 과제 제출합니다.

**Comment by sskim91** [comment]
12주차 과제 제출합니다.
https://amagrammer91.tistory.com/60

**Comment by gintire** [comment]
12주차 과제 제출합니다
https://gintrie.tistory.com/73

**Comment by tocgic** [comment]
12주차 과제 제출합니다.
https://github.com/tocgic/study-java-basic/blob/main/week12.md

**Comment by morethanmin** [comment]
과제 제출합니다!

https://moredevmin.tistory.com/22

**Comment by kgc0120** [comment]
12주차 과제 제출합니다!
https://gyucheolk.tistory.com/18

**Comment by thisisyoungbin** [comment]
https://young-bin.tistory.com/78 12주차 과제 제출합니다. 
부족한 부분들은 라이브를 돌려보며 보충할 예정입니다 !

**Comment by kyu9** [comment]
https://github.com/kyu9/WS_study/blob/master/week12.md
깜빡하고 과제제출이 늦어졌네요 ㅠㅠ 그래도 제출하겠습니다!

**Comment by JungHyeokMoon** [comment]
https://www.notion.so/12-a86d992b27414c6b9530c195fc2071d4

**Comment by roeniss** [comment]
https://velog.io/@roeniss/자바-기초지식-정리#12주차--어노테이션

**Comment by rockintuna** [comment]
12주차 과제 제출합니닷!
https://rockintuna.tistory.com/97

**Comment by loosie** [comment]
https://loosie.tistory.com/134

**Comment by rowanlee92** [comment]
12주차 과제 제출합니다!
https://watrv41.gitbook.io/devbook/java/java-live-study/12_week

**Comment by WonYong-Jang** [comment]
12주차 과제 제출합니다.
<https://wonyong-jang.github.io/java/2021/02/02/Java-annotation.html>

**Comment by highright96** [comment]
12주차 제출합니다!
https://github.com/highright96/java-study/blob/main/live-study/week12/week12.md

**Comment by pka0220z** [comment]
12주차 과제 제출합니다. 감사합니다
https://out-of-memory.tistory.com/18

**Comment by lkimilhol** [comment]
과제 제출 합니다.
https://github.com/lkimilhol/whiteship/blob/master/study/week12.md

**Comment by devShLee7017** [comment]
12주차 과제 제출합니다.
https://velog.io/@bluesky7017/%EC%95%A0%EB%85%B8%ED%85%8C%EC%9D%B4%EC%85%98

**Comment by cmg1411** [comment]
[12 주차 과제 제출합니다](https://alkhwa-113.tistory.com/entry/12%EC%A3%BC%EC%B0%A8-Annotation)

**Comment by Jason-time** [comment]
12주차 입니다.
https://github.com/Jason-time/java_study_with_whiteship/blob/main/mds/week12.md

**Comment by chaejunlee** [comment]
12주차 제출합니다!
https://www.notion.so/chaejunlee/12-84308dd878c34a79a0bfa95290857684

**Comment by ShimSeoungChul** [comment]
12주차 과제 제출합니다! 감사합니다.
https://scshim.tistory.com/265

**Comment by dacapolife87** [comment]
12주차 과제 제출합니다.
https://github.com/dacapolife87/javaStudy/blob/main/study/week12/Week12_annotation.md

**Comment by oktopman** [comment]
12주차 과제 늦게 제출합니다.
https://github.com/oktopman/java-live-study/blob/main/assignment/week12.md

**Comment by haeinoh** [comment]
12주차 과제 제출합니다. 감사합니다.

https://void2017.tistory.com/218

**Comment by gintire** [comment]
12주차 과제입니다.
https://gintrie.tistory.com/73

감사합니다.

**Comment by keunyop** [comment]
https://github.com/keunyop/java-study-with-whiteship/blob/main/live-study/week12.md

감사합니다.

**Comment by conyconydev** [comment]
12주차 과제 입니다.
https://roeldowney.tistory.com/499

**Comment by Ohzzi** [comment]
12주차 과제입니다.
https://velog.io/@ohzzi/Live-Study-12

**Comment by myBabyGrand** [comment]
[12주차입니다](https://github.com/myBabyGrand/study_JAVA_whiteship_live-study/blob/main/md_doc/12.Annotation.md)
이제 거의 다 따라 잡았네요

**Comment by Resilient923** [comment]
12주차 과제입니다!
https://resilient-923.tistory.com/128

**Comment by Park-SooYeon** [comment]
12주차 과제 제출합니다!
https://github.com/Park-SooYeon/today-I-learned/blob/master/live-study/annotation.md

**Comment by ShimSeoungChul** [comment]
12주차 과제 제출합니다!
https://scshim.tistory.com/265

**Comment by devHTak** [comment]
12주차 과제 제출합니다.

https://devhtak.github.io/java%20study/2021/02/16/StudyHalle_Week12.html

**Comment by ows3090** [comment]
12주차 과제 제출합니다
https://math-coding.tistory.com/182

**Comment by rshak8912** [comment]
12주차 과제 제출합니다
[12주차 과제](https://java-boy.tistory.com/114)

**Comment by jigmini** [comment]
늦었지만 12주차 과제 제출합니다!
https://blog.naver.com/jigmini/222252728842

**Comment by heewonham** [comment]
https://blog.naver.com/micky6414/222253156058

12줓 과제제출합니다 ^,^ 감사합니다!!

**Comment by kingsubin** [comment]
https://kingsubin.tistory.com/354

**Comment by GetMapping** [comment]
12주차 과제 제출합니다.
https://www.notion.so/12-Annotation-18dd73f2971b4954b1a1ff1b982fc8a0

**Comment by Hwanse** [comment]
12주차 과제를 제출합니다.

https://velog.io/@khsb2012/java-study-week12

**Comment by UmJaeJeong** [comment]
12주차 과제입니다.
https://blog.naver.com/umjaejeong2/222252933882

**Comment by loop-study** [comment]
12주차 과제입니다.
https://loopstudy.tistory.com/24

**Comment by sophysophysophysophy** [comment]
12주차 과제 제출합니다!
https://read-write-developer.tistory.com/126

**Comment by abcdsds** [comment]
12주차 과제 제출합니다.
https://www.notion.so/12-7c37f526f6e24927a63ae608f5132302

**Comment by daroguzo** [comment]
12주차 과제 제출합니다.
[https://github.com/daroguzo/JavaLiveStudy/commit/9351c23baaff7f4035612e69aec108b881a74b20](url)

**Comment by delusidiot** [comment]
https://delusidiot.tistory.com/entry/12-%EC%A3%BC%EC%B0%A8-%EA%B3%BC%EC%A0%9C-Enum
12추자 과제 제출합니다.

**Comment by soongjamm** [comment]
https://soongjamm.tistory.com/131

12주차 과제 제출합니다

**Comment by HyangKeunChoi** [comment]
https://geunyang93.tistory.com/54

12주차 입니다

**Comment by justinnn980** [comment]
https://justinnn980.tistory.com/20

**Comment by s0w0s** [comment]
https://www.notion.so/12-c23514b3412e418fb107ad61362a59c3
12주차 과제 제출합니다 ~

**Comment by jikimee64** [comment]
https://dncjf64.tistory.com/293
12주차 제출합니다!

**Comment by hhlyn0328** [comment]
12주차 과제입니다!
https://hongkey90.tistory.com/25

**Comment by JIN-096** [comment]
12주차 과제입니다.

**Comment by jaeeunis** [comment]
https://github.com/jaeeunis/TIL/blob/main/Java/Annotation.md
과제제출합니다.

**Comment by KwangJongJeon** [comment]
https://kj97.tistory.com/35
12주차 과제 제출합니다.

**Comment by shinnyoung** [comment]
12주차 과제 제출합니다!
https://parkbeaver.tistory.com/28

**Comment by younwony** [comment]
12주차 과제 입니다!
https://youn12.tistory.com/35

**Comment by jiwoo-choi** [comment]
12주차 과제입니다.
배운게 많았네요!
https://www.notion.so/12-Annotation-620d4f98becf46229e9304632536d064

**Comment by kongduboo** [comment]
[12주차 과제: 애노테이션](https://github.com/kongduboo/whiteship-java-study/blob/main/week12.md)
과제 입니다.

**Comment by geneaky** [comment]
12주차 과제입니다!
https://www.notion.so/WEEK-12-0c984708ffb84be7babd64ad649cbaca

**Comment by yskkkkkk** [comment]
12 주차 과제 제출합니다! 
https://knowing-today.blogspot.com/2021/02/12-12.html#more

**Comment by youngjinmo** [comment]
12주차 과제 제출합니다!
https://youngjinmo.github.io/2021/03/livestudy-week-12

**Comment by pond1029** [comment]
https://velog.io/@pond1029/annotation
늦었습니다.

**Comment by devvip** [comment]
12주차 과제 제출합니다!

https://velog.io/@eledev/JAVA-STUDYwith-whiteship-12주차-Annotation

**Comment by jeeneee** [comment]
12주차 과제 제출합니다.
https://jeeneee.dev/java-live-study/week12-annotation/

**Comment by DDOEUN** [comment]
12주차 과제 제출합니다.
https://teamo-oeun.tistory.com/19

**Comment by kdh9428** [comment]
12주차 과제 제출합니다!
https://www.notion.so/12-9bef4159744c463fbdfb4daf6d42f1ff

**Comment by Taein2** [comment]
https://codingrepo.tistory.com/41
12주차 제출합니당!

**Comment by yongtaelim** [comment]
https://jessyt.tistory.com/83
12주차 제출합니다!!

**Comment by eatnows** [comment]
https://eatnows.tistory.com/92
12주차입니다!

**Comment by YuSeungmo** [comment]
12주차입니다! 못한 부분은 마저 채우겠습니다.
https://github.com/YuSeungmo/java_study/blob/main/study/12%EC%A3%BC%EC%B0%A8.md

**Comment by JongWoonLee** [comment]
12주차입니다.
https://www.notion.so/12-71c1f30745184e9d8f5aab4cbb07e096

**Comment by hanseo0109** [comment]
12주차 과제입니다.
https://velog.io/@hanseo0109/step12-Java-Annotation
