### ISSUE TITLE
13주차 과제: I/O

### ISSUE THREAD

**Issue by whiteship** [whiteship/live-study#13]
# 목표
자바의 Input과 Ontput에 대해 학습하세요.

# 학습할 것 (필수)
* 스트림 (Stream) / 버퍼 (Buffer) / 채널 (Channel) 기반의 I/O
* InputStream과 OutputStream
* Byte와 Character 스트림
* 표준 스트림 (System.in, System.out, System.err)
* 파일 읽고 쓰기

# 마감일시
2021년 2월 20일 토요일 오후 1시까지.

**Comment by sujl95** [comment]
https://sujl95.tistory.com/71
13주차 과제입니다

**Comment by rlatmd0829** [comment]
https://wookcode.tistory.com/25
13주차 과제 제출하겠습니다!

**Comment by jymaeng95** [comment]
13주차 제출합니다!
https://velog.io/@zayson/백기선님과-함께하는-Live-Study-13주차-IO

**Comment by ssonsh** [comment]
13주차 과제 제출합니다. :) 

https://www.notion.so/I-O-af9b3036338c43a8bf9fa6a521cda242

**Comment by bingbingpa** [comment]
13주차 과제 제출합니다. 
https://bingbingpa.github.io/java/whiteship-live-study-week13

**Comment by gowoonsori** [comment]
13주차 제출합니다 :) 
새해 복 많이 받으세요
[https://gowoonsori.site/java/io](https://gowoonsori.site/java/io/)

**Comment by asqwklop12** [comment]
https://b-programmer.tistory.com/268
이거 진짜 힘드네요.
누군가 nio해주길 기도하고 있습니다. 이것도 하려고 햇는데 힘드네요 ㅜㅜ

**Comment by kyu9** [comment]
https://github.com/kyu9/WS_study/blob/master/week13.md
13주차 과제 제출합니다! 
새해 복 많이 받으세요~~

**Comment by Junhan0037** [comment]
13주차 과제 제출합니다.
https://www.notion.so/13-I-O-d53dce5b631d4debb5182137b76f1633

**Comment by loosie** [comment]
https://loosie.tistory.com/135

13주차 제출합니다~

**Comment by 1031nice** [comment]
새해 복 많이 받으세요 :)
https://github.com/1031nice/JavaStudy/blob/master/live-study/week13.md

**Comment by LeeGiCheol** [comment]
13주차 과제입니다!!
새해 복 많이 받으세요~~

감사합니다!!

https://leegicheol.github.io/whiteship-live-study/whiteship-live-study-13-IO/

**Comment by hyeonic** [comment]
13주차 과제 제출입니다!
https://hyeonic.tistory.com/112

**Comment by salmon2** [comment]
https://salmon2.github.io/java/2021/02/09/java-week13/

13주차 과제 입니다.

**Comment by SeungWoo-Oh** [comment]
13주차 과제입니다.
I/O관련 : [https://blog.naver.com/swoh1227/222237603565](https://blog.naver.com/swoh1227/222237603565)
NIO :[https://blog.naver.com/swoh1227/222244309304](https://blog.naver.com/swoh1227/222244309304)

**Comment by dongyeon94** [comment]
13주차 과제 제출합니다.

https://dblog94.tistory.com/entry/Java-Study-13%EC%9D%BC%EC%B0%A8

**Comment by Gomding** [comment]
13주차 과제 제출합니다.

https://parkadd.tistory.com/56

**Comment by JadenKim940105** [comment]
13주차 과제 제출하겠습니다 :) 
https://velog.io/@jaden_94/13주차-항해일지-IO

**Comment by rockintuna** [comment]
13주차 과제 제출합니닷
https://rockintuna.tistory.com/98

**Comment by hojunnnnn** [comment]
13주차 과제입니다.
https://dev-coco.tistory.com/27
새해복 많이 받으세요!

**Comment by KJJ924** [comment]
13주차 과제입니다
https://k3068.tistory.com/72

**Comment by reumongshop** [comment]
13주차 과제 첨부드립니다!~
https://blog.naver.com/reumongshop/222246981859

**Comment by cmg1411** [comment]
[I/O 과제 제출합니다](https://alkhwa-113.tistory.com/entry/IO)

**Comment by rkdals213** [comment]
https://www.notion.so/IO-58b47ed3d28249b6b9960d7866a6f03e

13주차 과제입니다

**Comment by Youngerjesus** [comment]
13주차 과제입니다

https://velog.io/@youngerjesus/%EC%9E%90%EB%B0%94-IO-Streams

**Comment by rowanlee92** [comment]
13주차 과제 제출합니다!
https://watrv41.gitbook.io/devbook/java/java-live-study/13_week

**Comment by ksundong** [comment]
13주차 과제 제출합니다!
https://velog.io/@dion/백기선님-온라인-스터디-13주차-IO

**Comment by Yadon079** [comment]
13주차 과제 제출합니다 :3
https://yadon079.github.io/2021/java%20study%20halle/week-13

**Comment by kjw217** [comment]
13주차 과제입니다.
https://github.com/kjw217/whiteship-live-study/blob/master/13th-week/13th-week.md

**Comment by giyeon95** [comment]
13주차 과제 제출합니다!

https://giyeon95.github.io/whiteship/whiteship_study_week13/

**Comment by KyungJae-Jang** [comment]
13주차 과제 제출합니다.
https://www.notion.so/13-I-O-c0b6bf03b34843309209e6c33ecdb4c9

**Comment by mongzza** [comment]
[13주차 과제](https://github.com/mongzza/java-study/blob/main/study/13%EC%A3%BC%EC%B0%A8.md)입니다. 감사합니다~

**Comment by JeongJin984** [comment]
13주차 과제 제출합니다.
https://github.com/JeongJin984/JeongJin984.github.io/blob/master/_posts/2021-02-19-Java-IO.md

**Comment by awesomeo184** [comment]
13주차 과제 제출합니다.
https://wisdom-and-record.tistory.com/59

**Comment by lkimilhol** [comment]
13 주차 과제 제출합니다
https://github.com/lkimilhol/whiteship/blob/master/study/week13.md

**Comment by hoi-hoon** [comment]
13주차 과제 제출합니다. 감사합니다!
https://hoi-hoon.github.io/study/live-study-13/

**Comment by inhalin** [comment]
13주차 과제 제출합니다.
https://github.com/inhalin/whiteship-live-study/blob/main/week13.md

**Comment by DevelopJKong** [comment]
13주차 과제 제출합니다 감사합니다!
https://blog.naver.com/tbaram10/222235434960

**Comment by haemin-jeong** [comment]
13주차 과제 제출합니다. 감사합니다:)
https://developer-hm.tistory.com/38

**Comment by dacapolife87** [comment]
13주차 과제 제출합니다!
https://github.com/dacapolife87/javaStudy/blob/main/study/week13/Week13_io.md

**Comment by gcha-kim** [comment]
13주차 과제 제출합니다.
https://www.notion.so/gcha/13-Week-I-O-a45fd1a5cd0241f0b8b18e3437bb33ce

**Comment by garlickim** [comment]
13주차 과제 제출합니다.
[https://github.com/garlickim/whiteship-live-java-study/week13](https://github.com/garlickim/whiteship-live-java-study/blob/main/%5Bweek13%5D%20IO.md)

**Comment by SJParkkk** [comment]
13주차 과제 제출합니다.
https://sjparkk.tistory.com/18

**Comment by good-influence** [comment]
13주차 과자 제출합니다.

https://www.notion.so/I-O-094fb5c7f8fa41fcb9876586ed3d92db

감사합니다.

**Comment by sungpillhong** [comment]
13주차 과제 제출입니다.

https://github.com/sungpillhong/whiteshipstudy/blob/master/13%EC%A3%BC%EC%B0%A8.md

이제 벌써 시즌1도 끝이보이네요 화이팅!!

**Comment by pej4303** [comment]
13주차 과제 제출합니다.
https://pej4303.tistory.com/63

**Comment by LeeWoooo** [comment]
13주차 과제 제출합니다~
https://github.com/LeeWoooo/Java_LiveStudy/tree/master/week13

**Comment by SooJungDev** [comment]
[13주차 과제](https://github.com/SooJungDev/TIL/blob/master/Java/live-study/13%EC%A3%BC%EA%B3%BC%EC%A0%9C.md) 제출합니다.

**Comment by Jangilkyu** [comment]
13주차 과제 제출합니다.
https://github.com/Jangilkyu/Java_Study/tree/main/Weeks13

**Comment by LeeJeongSeok** [comment]
13주차 과제 제출합니다.
- https://velog.io/@ljs0429777/13주차-과제-IO

과제를 수행하면서 알쏭달쏭한 부분이 생겨서 질문해봅니다.!!
io는 스트림기반이고 nio는 채널기반이라고 하는데.
제가 공부한 바로는 Channel 클래스는 자기 자신의 생성자를 통해 인스턴스화를 할 수 없고 오로지  InputStream/OutputStream 기반의 클래스가 생성된 후 getChannel()로 만들수 있다고 합니다. 그러면 결국 nio도 스트림기반이 될 수 있지 않을까요?

**Comment by redbean88** [comment]
https://github.com/redbean88/redbean88.github.io/blob/master/_posts/2021-02-17-whiteship-study-13week.md
13주차 과제 입니다.

**Comment by keunyop** [comment]
https://github.com/keunyop/java-study-with-whiteship/blob/main/live-study/week13.md

감사합니다.

**Comment by parker1609** [comment]
안녕하세요!
오늘도 과제를 마무리했네요ㅎㅎ 항상 감사드립니다.

[13주차 과제 링크](https://www.notion.so/13-I-O-acd572b7a4184a01813dc77ccfa591c8)

**Comment by numuduwer** [comment]
안녕하세요 과제제출합니다. 
부족해서 다른 분들의 글참고를 많이했습니다. 
라이브듣고나고 이주제도  자기걸로 만들겠습니다. 
https://www.notion.so/13-I-O-4cc242f8350f4d37bd2c113b7a450af4

**Comment by damho1104** [comment]
13주차 스터디 정리본입니다.
https://www.notion.so/damho1104/13-I-O-3d9c87f2f82741c4a75452a75f43b22c

**Comment by parksil0** [comment]
안녕하세요. 늦었지만 새해 복 많이받으세요!
https://github.com/parksil0/live-study/blob/master/13th_week.md

**Comment by ChoiGiSung** [comment]
https://github.com/ChoiGiSung/JavaStudy/blob/main/13%EC%A3%BC%EC%9E%90.md  
오늘 우아한 발표 잘 듣겠습니다!

**Comment by honux77** [comment]
[13주차 IO](https://velog.io/@honux/%EB%B0%B1%EA%B8%B0%EC%84%A0-%EC%9E%90%EB%B0%94-%EC%8A%A4%ED%84%B0%EB%94%94-13-IO)
오늘 알고리즘 대회가 있어서 좀 스터디 자료가 부실하네요 ㅜㅜ. (평소에도 부실하지만) 

참 지난주였나 기선님 막간광고(?) 덕분에 저렴한 샤오미 워터픽 구매했습니다. 짱짱 좋아요! 다른 분들도 꼭 써보세요!  감사합니다 ㅎㅎ. 이런 유용한 생활용품 소개도 좋을 것 같아요 ㅋㅋ. 

그리고 최근에 읽은 책 중 유닉스의 탄생이 무척 재미있었습니다. OS를 가볍게 접해 볼 수 있는 좋은 책인 것 같아요.

**Comment by sinchang1** [comment]
https://www.notion.so/Week_13-Baik-s-JAVA_STUDY-ab68e3ae5eeb48fb85a20e0a7e946ad4
새해복 많이 받으세요~

**Comment by doyoung0205** [comment]
https://doyoung.tistory.com/26

감사합니다 !

**Comment by Sungjun-HQ** [comment]
항상 감사합니다!
다른 분들 내용을 많이 참고하고 급하게 제출하느라 내용이 점점 메말라 가네요.
백수일 때가 좋았는데 ㅎㅎ

https://whereishq.blogspot.com/2021/02/13-io.html

**Comment by limyeonsoo** [comment]
https://www.notion.so/13-I-O-a3cc7ee765e74f018ea29b4d0220ae69
점점 나태해지는 것 같습니다. 조금 더 초심을 찾도록 노력해보겠습니다.
감사합니다.

**Comment by BrandPark** [comment]
안녕하세요. 13주차 과제입니다.
https://javanitto.tistory.com/11

**Comment by JJongSue** [comment]
13주차 과제입니다
https://github.com/JJongSue/javastudy/tree/master/src/main/java/week13

**Comment by etff** [comment]
13주차 과제입니다
https://itcoin.tistory.com/533

**Comment by ddings73** [comment]
13주차 과제입니다. 설날 지내고나니 나태해졌네요.. ㅠ
https://ddinsg73.tistory.com/27

**Comment by sskim91** [comment]
13주차 과제 제출합니다.
https://amagrammer91.tistory.com/66

**Comment by ksj0109188** [comment]
13주차 과제입니다.
https://jjunbbang.tistory.com/37

**Comment by KilJaeeun** [comment]
13주차 과제입니다.
https://kils-log-of-develop.tistory.com/575

**Comment by yky03** [comment]
13주차 과제입니다.  감사합니다.  
https://github.com/yky03/java-study-issues/blob/main/week13-io.md

**Comment by sellester** [comment]
https://blog.naver.com/sellester/222250598400

13주차 과제 제출합니다.

**Comment by Azderica** [comment]
https://azderica.github.io/13-java-study/
13주차 과제입니다.

**Comment by tocgic** [comment]
13주차 과제입니다.
https://github.com/tocgic/study-java-basic/blob/main/week13.md

**Comment by haeinoh** [comment]
13주차 과제 제출합니다. 감사합니다.

https://void2017.tistory.com/223

**Comment by monkeyDugi** [comment]
https://www.notion.so/13-I-O-16dfcad393004794bcf7d8b346d763ff

**Comment by yangseungin** [comment]
과제 제출을 안했었네요.
https://giantdwarf.tistory.com/60

**Comment by Resilient923** [comment]
13주차 과제 제출합니다
https://resilient-923.tistory.com/129

**Comment by conyconydev** [comment]
13주차 과제 제출합니다!
https://roeldowney.tistory.com/503

**Comment by kingsubin** [comment]
https://kingsubin.tistory.com/357

**Comment by Ohzzi** [comment]
13주차 과제 제출합니다
https://velog.io/@ohzzi/Live-Study-13

**Comment by Park-SooYeon** [comment]
13주차 과제 제출합니다.
https://github.com/Park-SooYeon/today-I-learned/blob/master/live-study/io.md

**Comment by chulphan** [comment]
13주차 과제 제출합니다.

감사합니다.

https://chulphan.tistory.com/16

**Comment by ows3090** [comment]
13주차 과제 제출합니다.
https://math-coding.tistory.com/manage/posts

**Comment by devHTak** [comment]
13주차 과제 제출합니다.

https://devhtak.github.io/java%20study/2021/02/23/StudyHalle_Week13.html

**Comment by azurealstn** [comment]
https://github.com/azurealstn/TIL/blob/main/java/live-study/week-13.md
13주자 제출합니다!

**Comment by jjone36** [comment]
13주차 과제 늦출합니다. 열심히 뒤쫓아가겠습니다!!
https://github.com/jjone36/self-study/blob/main/java_live_study/week13.md

**Comment by monkeyDugi** [comment]
https://www.notion.so/13-I-O-16dfcad393004794bcf7d8b346d763ff

**Comment by jikimee64** [comment]
13주차 IO 과제제출 합니다!
https://dncjf64.tistory.com/290

**Comment by abcdsds** [comment]
13주차 과제 제출합니다.
https://www.notion.so/13-I-O-d283a5f6549048ae91c1542832abb670

**Comment by daroguzo** [comment]
13주차 과제 제출합니다.
[https://github.com/daroguzo/JavaLiveStudy/blob/master/13.md](url)

**Comment by heewonham** [comment]
13주차 과제 제출합니다 ^,^

https://blog.naver.com/micky6414/222259677197

**Comment by yhh1056** [comment]
13주차 과제 제출합니다!

https://www.notion.so/aeno/I-O-11df3074b3854e6ca6719b2660dbdea8

**Comment by justinnn980** [comment]
https://justinnn980.tistory.com/21

**Comment by myBabyGrand** [comment]
[13주차 제출합니다!](https://github.com/myBabyGrand/study_JAVA_whiteship_live-study/blob/main/md_doc/13.IO.md)

**Comment by s0w0s** [comment]
https://www.notion.so/13-779c1a38242c40e39da70589bab9b7ce
13주차 과제 입니다 ~

**Comment by Lob-dev** [comment]
13주차 과제입니다.. ㄷㄷ 작성해놓고 코멘트 제출을 안해놨었네요. 

https://lob-dev.tistory.com/entry/Live-StudyWeek-13-IO

**Comment by thisisyoungbin** [comment]
13주차 과제 제출합니다.
https://young-bin.tistory.com/81

**Comment by haemanlee** [comment]
13주차 과제 제출합니다.

https://haemanlee.tistory.com/13
https://haemanlee.tistory.com/14

**Comment by sangwoobae** [comment]
늦었지만 13주차 과제 제출합니다!
https://blog.baesangwoo.dev/posts/java-livestudy-13week/

**Comment by kwj1270** [comment]
기존에 하던 일이 있어 많이 밀렸네요 마지막까지 열심히 달려보겠습니다.
[kwj1270 블로그](https://velog.io/@kwj1270/IO)

**Comment by ShimSeoungChul** [comment]
13주차 과제 제출합니다! 감사합니다.

https://scshim.tistory.com/283

**Comment by jaeeunis** [comment]
https://github.com/jaeeunis/TIL/blob/main/Java/I:O.md
과제제출합니다.

**Comment by joey3116** [comment]
13주차 과제 제출합니다.
[13주차과제](https://github.com/joey3116/live-study/blob/master/13week_assignment.md)

**Comment by jongyeans** [comment]
13주차 과제 제출합니다.
https://morebetterworld.tistory.com/15

**Comment by geneaky** [comment]
13주차 과제 제출합니다.
https://www.notion.so/WEEK13-de696919023a48c4b95475fae789f4af

**Comment by UmJaeJeong** [comment]
13주차 입니다~ 
https://blog.naver.com/umjaejeong2/222264154672

**Comment by rshak8912** [comment]
13주차 과제 제출합니다.
[13주차 과제](https://java-boy.tistory.com/115)

**Comment by kgc0120** [comment]
13주차 과제 제출합니다~
https://gyucheolk.tistory.com/21

**Comment by delusidiot** [comment]
13주차 과제 제출합니다.
https://delusidiot.tistory.com/entry/13-%EC%A3%BC%EC%B0%A8-%EA%B3%BC%EC%A0%9C-IO

**Comment by younwony** [comment]
13주차 과제 입니다!
https://youn12.tistory.com/36

**Comment by DDOEUN** [comment]
13주차 과제입니다.
https://teamo-oeun.tistory.com/20

**Comment by jiwoo-choi** [comment]
https://www.notion.so/13-I-O-39b704bee5af4a6b8a12ecc79acc1357
13주차 I/O 입니다! 모든 과제 완료 ~

**Comment by hhlyn0328** [comment]
13주차 과제 입니다 
https://hongkey90.tistory.com/26

**Comment by sunnynote** [comment]
안녕하세요. [13주차 과제](https://happyday3.tistory.com/83)입니다! 감사합니다.

**Comment by ysmiler** [comment]
[13주차](https://ysmiler.github.io/study/java/live-study/week13)

과제 제출합니다. 감사합니다!!
