### ISSUE TITLE
15주차 과제: 람다식

### ISSUE THREAD

**Issue by whiteship** [whiteship/live-study#15]
# 목표
자바의 람다식에 대해 학습하세요.

# 학습할 것 (필수)
* 람다식 사용법
* 함수형 인터페이스
* Variable Capture
* 메소드, 생성자 레퍼런스

# 마감일시
2021년 3월 6일 토요일 오후 1시까지.

**Comment by sujl95** [comment]
15주차 마지막 과제 제출입니다. 선장님 감사드리고 고생 정말 많으셨습니다
https://sujl95.tistory.com/76

**Comment by nimkoes** [comment]
15주차 과제 입니다.
https://blog.naver.com/hsm622/222260183401

**Comment by Lob-dev** [comment]
15주차 과제 제출합니다! 선장님 정말 감사합니다! ㅎㅎㅎ

https://lob-dev.tistory.com/entry/Live-StudyWeek-15-Lambda-Expression

**Comment by asqwklop12** [comment]
마지막 이네요.
조만간 시즌2할때까지 기다리겠습니다.!
https://b-programmer.tistory.com/279

**Comment by giyeon95** [comment]
마지막 주차 과제 제출합니다.
https://giyeon95.github.io/whiteship/whiteship_study_week15/

15주 동안 고생많으셨습니다. 감사합니다.

**Comment by ssonsh** [comment]
15주차 과제 제출합니다 ! 
다음 온라인 스터디가 더욱 기대됩니다. :)
https://www.notion.so/758e363f9fb04872a604999f8af6a1ae

**Comment by awesomeo184** [comment]
15주차 과제 제출합니다. 다들 그동안 고생 많으셨습니다.
https://wisdom-and-record.tistory.com/66

**Comment by joey3116** [comment]
15주차 과제 제출합니다.
[15주차 과제](https://github.com/joey3116/live-study/blob/master/15week_assignment.md)

**Comment by jaeeunis** [comment]
https://github.com/jaeeunis/TIL/blob/main/Java/Lambda.md
제출합니다! 마지막 과제~

**Comment by Yadon079** [comment]
15주차 과제 제출합니다 :3 
고생 많으셨습니다!
https://yadon079.github.io/2021/java%20study%20halle/week-15

**Comment by rowanlee92** [comment]
15주차 마지막 과제 제출합니다! 감사합니다!
https://watrv41.gitbook.io/devbook/java/java-live-study/15_week

**Comment by kwj1270** [comment]
15주차 마지막 과제 제출합니다.   
선장님과 처음으로 함께한 15주 정말 많은 것을 느끼고 성장했던 것 같아 감사드립니다.   
[kwj1270 블로그](https://github.com/kwj1270/TIL_JAVA/blob/master/15%20Lamda.md)

**Comment by jigmini** [comment]
15주차 과제입니다!
https://blog.naver.com/jigmini/222264615864

**Comment by hojunnnnn** [comment]
15주차 과제입니다.
https://dev-coco.tistory.com/29
감사합니다.

**Comment by LeeGiCheol** [comment]
안녕하세요 15주차 과제입니다!
스터디 기간동안 정말 많이 배웠습니다
고생 많으셨습니다 감사합니다!! 

https://leegicheol.github.io/whiteship-live-study/whiteship-live-study-15-lambda/

**Comment by SooJungDev** [comment]
[15주차 과제](https://github.com/SooJungDev/TIL/blob/master/Java/live-study/15%EC%A3%BC%EC%B0%A8%EA%B3%BC%EC%A0%9C.md)입니다. 감사합니다!

**Comment by gowoonsori** [comment]
15주차 과제 제출합니다.
[https://gowoonsori.site/java/lambda](https://gowoonsori.site/java/lambda/)

**Comment by sungpillhong** [comment]
https://github.com/sungpillhong/whiteshipstudy/blob/master/15%EC%A3%BC%EC%B0%A8.md

15주차 과제 제출합니다 기선님을 포함한 모든 스터디원분들 15주동안 고생하셨습니다.

**Comment by DevelopJKong** [comment]
https://blog.naver.com/tbaram10/222260716555

15주차 과제 입니다!!! 감사합니다!!!

**Comment by rockintuna** [comment]
안녕하세요! 15주차 과제 입니다.
선장님 이렇게 공부할 수 있는 기회 만들어 주셔서 너무 감사합니다요~
후기 꼭 하겠습니당!
https://rockintuna.tistory.com/107

**Comment by ddings73** [comment]
어느덧 벌써 15주차 과제를 제출하게 되었네요. 
그동안 감사했습니다!!!! 시즌 2때도 참석하고싶어요!!
https://ddinsg73.tistory.com/manage/posts/

**Comment by gcha-kim** [comment]
https://www.notion.so/gcha/15-Week-2169b24618094fca9e1d9b36d2f2bd95
15주차 과제 제출합니다.
긴 여정인데 그래도 무사히 끝마친것 같아 기분이 좋습니다.
많이 부족한점을 느꼈고 지금도 부족하다고 느끼지만 조금씩 조금씩 공부를 함에 있어 감사합니다.
시즌2때도 기대하겠습니다.
고생하셨습니다.!

**Comment by Azderica** [comment]
마지막주차 과제입니다.
https://azderica.github.io/15-java-study/

**Comment by loosie** [comment]
15주차 과제 제출합니다
https://loosie.tistory.com/140

이런 좋은 스터디 진행주셔서 정말 감사합니다 ^___^ 
해당 스터디를 진행하면서 Java에 대해 모르는게 많아 부족함을 많이 느꼈습니다 
정말 많은 것을 얻어가는 것 같습니다 

후에 이런 스터디를 또 여시면 무조건 다시 참가하겠습니다!

**Comment by jjone36** [comment]
시즌2에서 다시 만나요~ 정말 감사합니다!!
https://github.com/jjone36/self-study/blob/main/java_live_study/week15.md

**Comment by haemin-jeong** [comment]
15주차 과제 제출합니다.
어느덧 벌써 시즌1의 마지막 과제네요!! 좋은 시간 만들어주신 선장님과 스터디에 참여하신 모든 분들 감사하고, 고생하셨습니다 ㅎㅎ 
https://developer-hm.tistory.com/43

**Comment by KJJ924** [comment]
[15주차 과제](https://k3068.tistory.com/77)

**Comment by lkimilhol** [comment]
15주차 과제입니다.
기선님 고생많으셨고, 다들 고생 많으셨습니다.

https://github.com/lkimilhol/whiteship/blob/master/study/week15.md

**Comment by mongzza** [comment]
[15주차 과제](https://github.com/mongzza/java-study/blob/main/study/15%EC%A3%BC%EC%B0%A8.md)입니다.
그 동안 고생 많으셨습니다! 감사합니다~

**Comment by good-influence** [comment]
15주차 과제 제출합니다.

https://www.notion.so/a875fcd046db4ddd8dce01bf61743f5e

감사합니다.

**Comment by Gomding** [comment]
15주차 과제 제출합니다. 

https://parkadd.tistory.com/60

15주간 이끌어주셔서 정말 감사합니다.
이번에 자바에 대해서만 배운것이 아니라 공부방법, 글 정리, 등등 많은것을 배웠습니다.
좋은 스터디를 만들어주셔서 감사하고 스터디 참여하신분들께도 정말 감사드립니다.

**Comment by MoonHKLee** [comment]
마지막 과제 올립니다 정말 감사드립니다.
https://leemoono.tistory.com/30

**Comment by JeongJin984** [comment]
마지막 과제 제출합니다. 그동안 정말 감사드립니다.
https://github.com/JeongJin984/JeongJin984.github.io/blob/master/_posts/2021-03-05-Java-Lambda.md

**Comment by ksundong** [comment]
15주차 과제 제출합니다.
https://velog.io/@dion/백기선님-온라인-스터디-15주차-람다식

스터디 하는 동안 고생많으셨습니다. 덕분에 많은 인사이트도 얻고, 꾸준히 할 수 있는 동기가 되었던 것 같아요.
일과 다른 스터디, 리뷰어 활동 등을 하면서도 일단 참여한 이상 좋은 결과물은 만들지 못하더라도 꾸준히 했다는 마침표를 찍고자 했습니다.
하지만, 좋은 결과물을 만들어내지 못한건 많이 아쉽네요. 조금 벌려놓은 일들이 마무리 되면, 올라왔던 자료들을 보면서 다시 공부해봐야겠습니다.

그리고 쿠폰 잘 썼습니다! 감사해요!!

**Comment by garlickim** [comment]
15주차 과제 제출합니다. 그동안 고생 많으셨습니다. 감사합니다.  
[https://github.com/garlickim/whiteship-live-java-study/week15](https://github.com/garlickim/whiteship-live-java-study/blob/main/%5Bweek15%5D%20%EB%9E%8C%EB%8B%A4%EC%8B%9D.md)

**Comment by jiwoo-choi** [comment]
내일까지 남은 과제도 마무리해볼게요! 
이번 람다도 어렵긴 했지만 배운게 참 많았습니다.. :)
https://www.notion.so/15-757106032d85452cbc60cf1808d53978

**Comment by LeeWoooo** [comment]
https://github.com/LeeWoooo/Java_LiveStudy/tree/master/week15
람다는 조금 어렵네요...ㅎㅎ 
거의 4달동안 잘 배우고 갑니다 이 스터디로 인해 자신감을 얻고 꾸준히 무엇인가 할 수 있겠다라는 생각이 들었습니다

**Comment by thisisyoungbin** [comment]
https://young-bin.tistory.com/84
15주차 마지막 과제 제출합니다. 실제론 16~17주가 소요됐는데 그 동안 수고하셨습니다.
시즌 2에서 봬요!

**Comment by dacapolife87** [comment]
15주차 과제 제출합니다.

https://github.com/dacapolife87/javaStudy/blob/main/study/week15/Week15_lambda.md

그동안 스터디를 진행하면서 많은것을 배우게 된 뜻깊은 시간이였습니다.
이런 자리를 만들어주셔서 감사합니다 ^^

**Comment by Yo0oN** [comment]
과제 제출합니다! 이렇게 스터디를 할 수 있어서 너무 좋았습니다. 감사합니다!

[15주차 람다식](https://github.com/Yo0oN/Tech-Study/blob/master/posts/Java/015.%EB%9E%8C%EB%8B%A4%EC%8B%9D.md)

**Comment by SJParkkk** [comment]
과제 제출합니다 !
[15주차 람다식](https://sjparkk.tistory.com/20)

**Comment by 9m1i9n1** [comment]
과제 제출합니다. 

[15주차 과제](https://github.com/9m1i9n1/TIL_Today-I-Learned/blob/master/05_Java/03_liveStudy/15_%EB%9E%8C%EB%8B%A4%EC%8B%9D.md)

**Comment by LeeJeongSeok** [comment]
15주차 과제 제출합니다.
 
여태껏 스터디를 진행하느라 고생많으셨습니다. (거의 끝판이라..좀 얼렁뚱땅..대충한 경향이 있지만..)
그동안 스터디를 하면서 많은 것들을 배울 수 있었고, 라이브 방송도 볼때마다 유익해서 너무 좋은 시간이였습니다! 감사합니다.

- https://velog.io/@ljs0429777/15주차-과제-람다식

**Comment by rshak8912** [comment]
15주차 과제 제출합니다.
[15주차](https://java-boy.tistory.com/119)

이번 스터디가 저한테 엄청 도움이 된 스터디 임이 자명하지만 뒤로 갈수록 의지가 줄어들어 설렁설렁한게 제 자신한테 너무 아쉬움이 남네요. 하지만 스터디 하면서 공부하고, 생방송 참여하면서 책 소개부터 해서 값진 시간이었습니다!
스터디 2기를 시작하게 된다면 초심으로 돌아가 다시 열심히 해보고 싶습니다 :)

**Comment by 2yeseul** [comment]
15주차 과제 제출합니다!
https://github.com/2yeseul/TIL/blob/master/Java/Lamda.md
수고하셨습니다!!!!

**Comment by choiyoungkwon12** [comment]
15주차 과제 제출합니다.
https://cyk0825.tistory.com/31

**Comment by etff** [comment]
15주차 과제 제출합니다.
https://itcoin.tistory.com/553

**Comment by ahyz0569** [comment]
15주차 과제입니다. 스터디 이끌어주셔서 감사합니다!
https://github.com/ahyz0569/Study/blob/main/Java-study/week_015_lambda.md

**Comment by hhlyn0328** [comment]
15주차 과제입니다
https://hongkey90.tistory.com/28

**Comment by Sungjun-HQ** [comment]
https://whereishq.blogspot.com/2021/03/15.html

너무 소중한 시간이었습니다.

**Comment by jymaeng95** [comment]
https://www.notion.so/Live-Study-15-165093dc6577454c94f81946b318f006

15주 동안 감사합니다! 마지막 과제 제출합니다.!

**Comment by parker1609** [comment]
안녕하세요!
드디어 마지막 과제를 제출하게 되었습니다. 그동안 고생하셨고, 정말 감사드립니다. ㅎㅎ
새로운 스터디 방식을 경험해보았는데, 뜻 깊은 경험이었습니다. 다음에 또 스터디가 있다면 참석하고 싶어요!

[과제 링크](https://www.notion.so/15-4e44fa299fb04f6b96bc46155beec8a6)

**Comment by justinnn980** [comment]
https://justinnn980.tistory.com/23

**Comment by ChoiGiSung** [comment]
https://github.com/ChoiGiSung/JavaStudy/blob/main/15%EC%A3%BC%EC%B0%A8.md  
생애 처음으로 스터디라는 것도 해보고 좋은 경험이었습니다.
선장님의 노고에 감사드립니다!

**Comment by limyeonsoo** [comment]
https://www.notion.so/15-c7bc1fd1c1a14432b3d9c3c948fc1cc7
15주 동안 모두들 고생하셨고 감사합니다.

**Comment by chulphan** [comment]
마지막 과제 제출합니다

그동안 너무 고생 많으셨고 감사드립니다

https://chulphan.tistory.com/manage/posts

**Comment by redbean88** [comment]
15주차 과제입니다 고생하셨습니다
https://redbean88.github.io/study/whiteship-study-15week/

**Comment by honux77** [comment]
[15주차 람다 스터디](https://velog.io/@honux/%EB%B0%B1%EA%B8%B0%EC%84%A0-%EC%9E%90%EB%B0%94-%EC%8A%A4%ED%84%B0%EB%94%94-15-%EB%9E%8C%EB%8B%A4)

드디어 스터디를 마쳤네요. 항상 입문책을 다시 읽어야지라고 생각했는데, 기선님 아니었으면 못했을 거예요!
다른 분들의 양질의 자료 덕분에 배운 내용도 너무 많았습니다.
모두 감사합니다.

**Comment by 1031nice** [comment]
고생 많으셨습니다. 감사합니다.

https://github.com/1031nice/JavaStudy/blob/master/live-study/week15.md

**Comment by haeinoh** [comment]
15주차 과제 제출합니다. 감사합니다.

https://void2017.tistory.com/229

**Comment by delusidiot** [comment]
마지막 15주차 과제 제출합니다.
https://delusidiot.tistory.com/entry/15-%EC%A3%BC%EC%B0%A8-%EA%B3%BC%EC%A0%9C-%EB%9E%8C%EB%8B%A4%EC%8B%9D

**Comment by HyangKeunChoi** [comment]
마지막 15주차 과제입니다.
감사합니다.
https://geunyang93.tistory.com/56

**Comment by monkeyDugi** [comment]
https://www.notion.so/15-db1ddbd5fc2e4971ae67b0fe39b8cd1a

**Comment by Jangilkyu** [comment]
15주차 마지막 과제 제출합니다.! 스터디 하면서 이해 안되고 넘어간 내용도 있었지만 나중에 공부하거나 필요할 때 다시 찾아서 볼 수 기회를 주셔서 감사했습니다.
https://github.com/Jangilkyu/Java_Study/tree/main/Weeks15

**Comment by JJongSue** [comment]
고생하셨습니다. 많은 도움 되었습니다.
https://github.com/JJongSue/javastudy/tree/master/src/main/java/week15

**Comment by yeGenieee** [comment]
15주차 과제 제출합니다. 15주간 이끌어주셔서 감사합니다 !
https://github.com/yeGenieee/java-live-study/blob/main/%5B15%5DJava%20Live%20Study.md

**Comment by sinchang1** [comment]
마지막과제 제출합니다!
다시 수정 계속 할게요~!^^
https://www.notion.so/Week_15-Baik-s-JAVA_STUDY-f25edb6ebeda4117a4e94d306e6172ef

**Comment by parksil0** [comment]
올리는 걸 깜빡했네요 ...ㅜ
마지막 과제입니다.
15주동안 많이 배웠습니다. 감사합니다!
https://github.com/parksil0/live-study/blob/master/15th_week.md

**Comment by rlatmd0829** [comment]
15주차 과제 제출합니다!
스터디를 진행하면서 많이 성장할 수 있었던것 같습니다!

**Comment by Resilient923** [comment]
스터디 끝까지 하길 정말 잘했네요! 감사했습니다!
https://resilient-923.tistory.com/135

**Comment by sangwoobae** [comment]
늦었지만.. 마지막까지 완료하였습니다. 감사합니다!
https://blog.baesangwoo.dev/posts/java-livestudy-15week/

**Comment by enothfif** [comment]
늦었지만 시작해봅니다.
지난 과제 공부해서 시즌2는 처음부터 참여하겠습니다. 감사합니다.
https://enothfif.tistory.com/2

**Comment by yky03** [comment]
15주차 과제 제출합니다. 1시즌 스터디 하시느라 그간 고생하셨습니다!
https://github.com/yky03/java-study-issues/blob/main/week15-lamda.md

**Comment by oktopman** [comment]
15주차 과제 제출합니다.
https://github.com/oktopman/java-live-study/blob/main/assignment/week15.md
