### ISSUE TITLE
8주자 과제: 인터페이스

### ISSUE THREAD

**Issue by whiteship** [whiteship/live-study#8]
# 목표
자바의 인터페이스에 대해 학습하세요.

# 학습할 것 (필수)
* 인터페이스 정의하는 방법
* 인터페이스 구현하는 방법
* 인터페이스 레퍼런스를 통해 구현체를 사용하는 방법
* 인터페이스 상속
* 인터페이스의 기본 메소드 (Default Method), 자바 8
* 인터페이스의 static 메소드, 자바 8
* 인터페이스의 private 메소드, 자바 9

# 마감일시
2021년 1월 9일 토요일 오후 1시까지.

**Comment by LeeGiCheol** [comment]
https://leegicheol.github.io/whiteship-live-study/whiteship-live-study-08-interface/

8주차 과제 제출합니다!!
감사합니다!! 😄

**Comment by ssonsh** [comment]
8주차 과제 제출합니다. :)

https://www.notion.so/4b0cf3f6ff7549adb2951e27519fc0e6

**Comment by asqwklop12** [comment]
https://b-programmer.tistory.com/248

8주차 과제 제출합니다.!

**Comment by rlatmd0829** [comment]
https://wookcode.tistory.com/19?category=979588

8주차 과제제출 합니다!

**Comment by sujl95** [comment]
https://sujl95.tistory.com/60
8주자 과제 입니다

**Comment by mongzza** [comment]
[8주차 과제](https://github.com/mongzza/java-study/blob/main/study/8%EC%A3%BC%EC%B0%A8.md)입니다. 감사합니다~

**Comment by sangwoobae** [comment]
https://blog.baesangwoo.dev/posts/java-livestudy-8week/
8주차 과제 제출합니다~! 감사합니다 👍

**Comment by hojunnnnn** [comment]
8주차 과제입니다.
https://dev-coco.tistory.com/13
감사합니다

**Comment by Youngerjesus** [comment]
https://velog.io/@youngerjesus/%EC%9E%90%EB%B0%94-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4

8주차 과제 제출합니다 감사합니다

**Comment by UmJaeJeong** [comment]
8주차 스터디 과제입니다.!!
열심히 따라가겠습니다.
https://blog.naver.com/umjaejeong2/222196618407

**Comment by Lob-dev** [comment]
https://lob-dev.tistory.com/entry/Live-StudyWeek-08-인터페이스

8주차 과제 제출합니다!!!!!!

**Comment by SeungWoo-Oh** [comment]
8주차 과제 제출합니다.
[https://blog.naver.com/swoh1227/222196781438](https://blog.naver.com/swoh1227/222196781438)

**Comment by githubjam2** [comment]
8주차 과제제출합니다
https://blog.naver.com/shpain2/222196045386

**Comment by Yadon079** [comment]
8주차 과제 제출합니다 :3
https://yadon079.github.io/2021/java%20study%20halle/week-08

**Comment by jymaeng95** [comment]
8주차 과제 제출합니다!
https://velog.io/@zayson/백기선님과-함께하는-Live-Study-8주차-인터페이스

**Comment by hyeonic** [comment]
8주차 과제 제출입니다!
https://hyeonic.tistory.com/38

**Comment by KJJ924** [comment]
8주차 과제 제출
https://k3068.tistory.com/34

**Comment by jongnan** [comment]
8주차 과제 제출합니다~🙌🏻
* [인터페이스](https://github.com/jongnan/Java_Study_With_Whiteship/blob/master/week8/week8.md)

**Comment by league3236** [comment]
8주차 과제 제출합니다.

https://github.com/league3236/startJava/blob/master/live_study/week8.md

**Comment by KilJaeeun** [comment]
8주차 과제 제출합니다.
https://kils-log-of-develop.tistory.com/437

**Comment by sejongdeveloper** [comment]
선장님 8주차 과제 제출합니다!
https://blog.naver.com/sejonghumble/222198890478

**Comment by ddings73** [comment]
8주차 과제 제출합니다.
https://github.com/ddings73/Study/blob/main/Java_live-study/%EA%B0%9C%EB%85%90%EC%A0%95%EB%A6%AC/week08.md

**Comment by jeeneee** [comment]
8주차 과제 제출합니다. 감사합니다.
https://jeeneee.dev/java-live-study/week8-interface/

**Comment by kjw217** [comment]
8주차 과제입니다.
https://github.com/kjw217/whiteship-live-study/blob/master/8th-week/8th-week.md

**Comment by Chohongjae** [comment]
https://chohongjae.github.io/livestudy/live-study-week8/
8주차 과제입니다.

**Comment by heonjun91** [comment]
8주차 과제입니다.
https://github.com/heonjun91/javalivestudy/blob/master/src/main/java/com/javalivestudy/assignment8/assignment8.md

**Comment by minikuma** [comment]
8주차 과제 제출 합니다. 감사합니다. : )
https://www.notion.so/8-c057a46e1970469b8e7ecf228cd40831

**Comment by ShimSeoungChul** [comment]
8주차 과제 제출 합니다. 감사합니다!
https://scshim.tistory.com/228

**Comment by hoi-hoon** [comment]
8주차 과제 제출합니다!
https://hoi-hoon.github.io/study/live-study-8/

**Comment by jjone36** [comment]
과제 제출합니다! 
https://github.com/jjone36/self-study/blob/main/java_live_study/week08.md

**Comment by boraborason** [comment]
https://github.com/boraborason/java_livestudy/blob/main/8week%20%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4.md 8주차 과제

**Comment by etff** [comment]
8주차 과제 제출합니다.
https://itcoin.tistory.com/489

**Comment by Junhan0037** [comment]
8주차 과제 제출입니다!
https://www.notion.so/8-55217f5b29c34399bc6eb4876da6f208

**Comment by WonYong-Jang** [comment]
8주차 과제 제출합니다.
[https://wonyong-jang.github.io/java/2021/01/04/Java-Interface](https://wonyong-jang.github.io/java/2021/01/04/Java-Interface.html)

**Comment by damho1104** [comment]
8주차 스터디 정리본 제출합니다.
https://www.notion.so/damho1104/8-a9a14fb3469a4a75a2f1490acb1c32e8
이번에는 **스터디 시간에 같이 이야기해 볼 수 있는 문제** 를 내봤습니다.
문제는 **인터페이스 상속** 파트에 있습니다.

**Comment by Yo0oN** [comment]
8주차 제출합니다.
[8주차 과제](https://github.com/Yo0oN/Tech-Study/blob/master/posts/Java/008.%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4.md)

**Comment by garlickim** [comment]
8주차 과제 제출합니다. 감사합니다.
[https://github.com/garlickim/whiteship-live-java-study/week8](https://github.com/garlickim/whiteship-live-java-study/blob/main/%5Bweek8%5D%20%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4.md)

**Comment by lee-maru** [comment]
8주차 과제 입니다 : )
[자바 8이후의 인터페이스](https://catch-me-java.tistory.com/44)
[자바 8이전의 인터페이스](https://catch-me-java.tistory.com/45)

**Comment by SooJungDev** [comment]
8주차 과제 제출합니다. 감사합니다!
- [8주차 과제](https://github.com/SooJungDev/TIL/blob/master/Java/live-study/8%EC%A3%BC%EC%B0%A8%EA%B3%BC%EC%A0%9C.md)

**Comment by jiwoo-choi** [comment]
https://www.notion.so/Java-8-0cc8c251d5374ac882a4f22fa07c4e6a
8주차 과제 제출합니다.

**Comment by 2yeseul** [comment]
8주차 괴제 제출합니다~
https://seulog.netlify.app/Baekjoon/week8/

**Comment by 2yeseul** [comment]
8주차 과제 제출합니다~
https://seulog.netlify.app/Java/week8/

**Comment by ByungJun25** [comment]
8주차 과제 제출합니다.
https://github.com/ByungJun25/study/tree/main/java/whiteship-study/8week

인터페이스의 `default` 메서드에 대해 많이 알아 볼 수 있었습니다.
감사합니다. 👍

**Comment by ChoiGiSung** [comment]
과제 제출이요~
https://github.com/ChoiGiSung/JavaStudy/blob/main/8%EC%A3%BC%EC%B0%A8.md
인터페이스의 여러 기능을 처음 알았어요!

**Comment by 9m1i9n1** [comment]
과제 제출합니다. 감사합니다!

[8주차 과제](https://github.com/9m1i9n1/TIL_Today-I-Learned/blob/cb0e2c45ad485a9409e499bb34177f87694db5f0/05_Java/03_liveStudy/08_%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4.md)

**Comment by kyu9** [comment]
https://github.com/kyu9/WS_study/blob/master/week8.md
8주차 과제입니다~

**Comment by yhh1056** [comment]
늦게 시작하여 반필 티는 물 건너갔지만 이번 주부터 시작하여 항해를 완주해보겠습니다.
감사합니다.
[8주차 인터페이스](https://www.notion.so/45d25978bde84d94ade14b93493bdb29)

**Comment by chulphan** [comment]
8주차 과제 제출합니다

감사합니다
https://chulphan.tistory.com/11

**Comment by ksj0109188** [comment]
8주차 과제 제출합니다!
https://jjunbbang.tistory.com/10

**Comment by haemin-jeong** [comment]
8주차 과제 제출합니다 감사합니다!!
https://developer-hm.tistory.com/29

**Comment by iseunghan** [comment]
https://iseunghan.tistory.com/266
8주차 과제 제출합니다!

**Comment by KyungJae-Jang** [comment]
8주차 과제 제출합니다.
감사합니다!
https://www.notion.so/8-cdc4ef154c784babacb11955240cb931

**Comment by thisisyoungbin** [comment]
8주차 인터페이스 과제 제출합니다 :)
https://young-bin.tistory.com/74

**Comment by pka0220z** [comment]
8주차 과제 제출합니다.
https://out-of-memory.tistory.com/13

**Comment by good-influence** [comment]
8주차 과제 제출합니다. 

https://www.notion.so/5950eb7d89054247b41e552410998d23

감사합니다.

**Comment by doyoung0205** [comment]
8주차 과제 제출합니다. 

[과제링크](https://doyoung.tistory.com/21)

**Comment by MoonHKLee** [comment]
https://leemoono.tistory.com/23

- 자바 8 이후에 인터페이스와 추상메서드가 하는 역할이 똑같다고 생각합니다. 그렇다면 구조의 확장 측면에서 무조건 인터페이스를 사용하는것이 옳은것같은데 추상메서드가 있어야 하는 이유가 궁금합니다.

**Comment by ksundong** [comment]
8주차 과제 제출합니다.
https://velog.io/@dion/백기선님-온라인-스터디-8주차-인터페이스

**Comment by ZhenxiKim** [comment]
8주차 과제 제출합니다.
https://zhenxikim.tistory.com/26

**Comment by limyeonsoo** [comment]
8주차 과제입니다.
https://www.notion.so/8-3012fd7c929c4f939a378db305c005f8#be8449363cce402687c6a66f5789a60c

**Comment by sombrero104** [comment]
8주차 과제입니다! 감사합니다 (__)
https://github.com/gtpe/java-study/blob/master/w8.md

**Comment by clap1030** [comment]
8주차 과제제출입니다. 감사합니다.

https://i-am-clap.tistory.com/11

**Comment by Resilient923** [comment]
https://resilient-923.tistory.com/108

8주차 과제입니다!!

**Comment by devShLee7017** [comment]
https://velog.io/@bluesky7017/%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4
8주차 과제입니다.

**Comment by GetMapping** [comment]
https://www.notion.so/8-7eeba29e234e45a58234b6c4f62aab5b
8주차 과제입니다.

**Comment by cocodori** [comment]
8주차 과제입니다.

https://coco-log.tistory.com/125

**Comment by DevelopJKong** [comment]
8주차 과제입니다
https://blog.naver.com/tbaram10/222196327557

**Comment by ohsg0226** [comment]
8주차 과제입니다
https://ohsg0226.tistory.com/2

**Comment by nimkoes** [comment]
8주차 과제 입니다.
https://blog.naver.com/hsm622/222201314752

**Comment by Azderica** [comment]
8주차 과제제출합니다.
https://azderica.github.io/00-java-interface

**Comment by gcha-kim** [comment]
8주차 과제입니다.
https://www.notion.so/gcha/8-Week-bd802ef69b0a41a1b384cff14ee56fe3

**Comment by tbnsok40** [comment]
8주차 과제 제출합니다 내일뵙겠습니다 👍🏻  https://junior-datalist.tistory.com/55

**Comment by pej4303** [comment]
8주차 과제 제출합니다:smile:
https://pej4303.tistory.com/58

**Comment by bingbingpa** [comment]
8주차 과제 제출합니다.
https://bingbingpa.github.io/java/whiteship-live-study-week8/

**Comment by LeeWoooo** [comment]
8주차 과제입니다 감사합니다:)
https://github.com/LeeWoooo/Java_LiveStudy/tree/master/week8

**Comment by Gomding** [comment]
8주차 과제 승선합니다 🚢 
https://parkadd.tistory.com/46

**Comment by SJParkkk** [comment]
8주차 과제 제출합니다 👍 
https://sjparkk.tistory.com/10

**Comment by dacapolife87** [comment]
8주차 과제 제출합니다
https://github.com/dacapolife87/javaStudy/blob/main/study/week08/Week08_interface.md

**Comment by inhalin** [comment]
https://github.com/inhalin/whiteship-live-study/blob/main/week-08.md

과제 마지막 부분의 private 메소드 부분 공부하면서 참고한 코드가 잘 이해가 안돼서요.. 혹시 라이브 수업때 조금 설명을 해주실 수 있을까요?

**Comment by rockintuna** [comment]
안녕하세요. 8주차 과제 제출합니다.
https://rockintuna.tistory.com/83

**Comment by LeeJeongSeok** [comment]
과제 제출합니다.
https://velog.io/@ljs0429777/8주차-과제-인터페이스

이번 과제를 공부하다 보니 깊게 공부했다기보단 의식의 흐름이 더 큰 거 같습니다..
자바 8버전에서 지원하는 static, default, function을 공부하면서 느낀거지만 이제는 추상 클래스가 필요 없지 않을까요?? 이 부분에 대해서 선장님에 대한 생각도 궁금합니다!

**Comment by Jangilkyu** [comment]
8주차 과제 제출합니다. :)
https://github.com/Jangilkyu/Java_Study/tree/main/Week8

**Comment by GGob2** [comment]
8주차 과제 제출합니다!! 🔥 
https://velog.io/@ggob_2/java-study-8

**Comment by numuduwer** [comment]
8주차 과제 제출합니다. 
https://www.notion.so/8-92973a4211454e0f8103f78b9f3b71c8

**Comment by chlaudeh** [comment]
8주차 과제 제출합니다

https://blog.naver.com/chlaudeh/222201534115

**Comment by keunyop** [comment]
https://github.com/keunyop/java-study-with-whiteship/blob/main/live-study/week8.md

감사합니다.

**Comment by ysmiler** [comment]
[8주차](https://ysmiler.github.io/study/java/live-study/week8/)

과제 제출합니다. 감사합니다!!

**Comment by tocgic** [comment]
8주차 과제 제출드립니다.
https://github.com/tocgic/study-java-basic/blob/main/week8.md
감사합니다.

**Comment by Sungjun-HQ** [comment]
https://whereishq.blogspot.com/2021/01/8.html

감사합니다~

**Comment by castleCircle** [comment]
8주차 과제 제출했습니다.
https://castleone.tistory.com/11

**Comment by Ahnyezi** [comment]
8주차 과제 제출합니다! 

- [과제: 자바의 인터페이스](https://ahnyezi.github.io/java/javastudy-8-interface/)

**Comment by YeseulDo** [comment]
8주차 과제제출합니다:)
https://github.com/YeseulDo/JavaStudy_STUDYHALLE/blob/main/WEEK8/WEEK%238.md

**Comment by JJongSue** [comment]
https://github.com/JJongSue/javastudy/tree/master/src/main/java/week8
8주차 과제입니다

**Comment by RealSong88** [comment]
8주차 과제 제출합니다~~
https://www.notion.so/8-c9cb3fdc26fe4d2b89a095247ca5e01f

**Comment by parksil0** [comment]
8주차 과제입니다. 감사합니다!
https://github.com/parksil0/live-study/blob/master/08th_week.md

**Comment by ohhhmycode** [comment]
8주차 공부한 내용 입니다!
https://ohhhmycode.tistory.com/12

**Comment by hongminpark** [comment]
9주차 과제 제출합니다. :) https://hongminpark.github.io/2021-01-08/studyhalle08

**Comment by soongjamm** [comment]
8주차 공부입니당
https://soongjamm.tistory.com/119

**Comment by CODEMCD** [comment]
안녕하세요.
8주차 과제 제출합니다.
[8주차 과제](https://www.notion.so/8-33c268d2cdb34c9a822c420f0154d3de)

감사합니다!

**Comment by sinchang1** [comment]
8주차 과제입니다~
https://www.notion.so/Week_8-Baik-s-JAVA_STUDY-f891f5bd46cb447ca7e4384ee085f80f

**Comment by giyeon95** [comment]
8주차 과제 제출합니다.

https://giyeon95.github.io/whiteship/whiteship_study_week08/

감사합니다.

**Comment by integer87** [comment]
8주차 과제 제출합니다.
늦게 참여하게되었는데 스터디가 처음이어서 스터디 방법에 있어서 잘못된점 있으면 알려주시면 고쳐서 진행하도록 하겠습니다.
감사합니다.
https://github.com/integer87/study/blob/master/chapter8/chapter8.md

**Comment by s0w0s** [comment]
8주차 과제 제출 합니다
https://www.notion.so/8-5f7d355b8307492abb20ee9f20983da4

**Comment by yeGenieee** [comment]
8주차 과제 제출합니다 ~
https://github.com/yeGenieee/java-live-study/blob/main/%5B8%5DJava%20Live%20Study.md

**Comment by 1031nice** [comment]
한국은 날이 많이 춥네요. 건강 조심하세요!
https://github.com/1031nice/JavaStudy/blob/master/live-study/week8.md

**Comment by yky03** [comment]
8주차 과제 제출합니다. 감사합니다.
https://github.com/yky03/java-study-issues/blob/main/week8-interface.md

**Comment by redbean88** [comment]
https://redbean88.github.io/study/whiteship-study-8week/
8주차 과제입니다 감사합니다

**Comment by yangseungin** [comment]
인터페이스 과제 제출합니다
https://giantdwarf.tistory.com/47

**Comment by honux77** [comment]
안녕하세요? 선장님과 선원님들 모두 감사합니다. 

참 저희는 익명 설문에 sli.do 쓰는데 수업기간 동안 링크를 재공유할 필요가 없어서 편해요. 한 번 검토해 보세요1

[8주차 스터디 과제 인터페이스 링크](https://velog.io/@honux/%EB%B0%B1%EA%B8%B0%EC%84%A0-%EC%9E%90%EB%B0%94-%EB%9D%BC%EC%9D%B4%EB%B8%8C-%EC%8A%A4%ED%84%B0%EB%94%948-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4)

**Comment by jwsims1995** [comment]
https://won-percent.tistory.com/68

8주차 과제입니다.

**Comment by anna9001** [comment]
https://ssseung.tistory.com/69

감사합니다

**Comment by sjinjin7** [comment]
https://kimvampa.tistory.com/125

8주차 과제입니다.

**Comment by abcdsds** [comment]
과제 제출합니다.

https://www.notion.so/8-0daf5da77c734621b61ccc2d46b904f2

**Comment by JeongJin984** [comment]
8주차 과제입니다: https://github.com/JeongJin984/JeongJin984.github.io/blob/master/_posts/2021-01-09-Java-Interface.md

**Comment by resister12** [comment]
https://www.notion.so/8-dc1a3d0dbda945ecb867bbc1fca35da8

8주차 과제 제출합니다.

**Comment by kingsubin** [comment]
https://kingsubin.tistory.com/332

**Comment by Parkyunhwan** [comment]
https://www.notion.so/8-97d3433f328b41578beb89a2292d5845

8주차 과제 제출합니다.

**Comment by dmstjd1024** [comment]
https://dmstjd1024.github.io/2021/01/08/live-study8.html
이런 올린줄 알았네요 ㄷㄷ 8주차 과제 제출합니다!

**Comment by rshak8912** [comment]
8주차 과제제출합니다.
[8주차 과제](https://java-boy.tistory.com/87?category=982755)

**Comment by gtpe** [comment]
다른 아이디로 잘못 올려서 다시 올립니다 ㅠㅠ
https://github.com/gtpe/java-study/blob/master/w8.md

**Comment by jigmini** [comment]
8주차 과제 입니다!
https://blog.naver.com/jigmini/222201829702

**Comment by Jason-time** [comment]
https://github.com/Jason-time/java_study_with_whiteship/blob/main/mds/week08.md
8주차 과제 링크입니다. :)

**Comment by jaxx2001** [comment]
https://hanseo0109.tistory.com/7
8주차 과제 제출합니다.

**Comment by haenyilee** [comment]
https://haenyilee.github.io/Java/whiteship-study-halle/%5B8%EC%A3%BC%EC%B0%A8%5D%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4.html

8주차 과제 제출합니다!

**Comment by minzzang** [comment]
8주차 과제입니다.
https://minzzang.tistory.com/7

**Comment by sungpillhong** [comment]
https://github.com/sungpillhong/whiteshipstudy/blob/master/8%EC%A3%BC%EC%B0%A8.md

8주차 과제입니다. 시간계산을 잘못해서 처음으로 제시간에 못했네요 ㅠ

**Comment by sskim91** [comment]
8주차 과제 제출합니다.
https://amagrammer91.tistory.com/51

**Comment by kgc0120** [comment]
8주차 과제 제출합니다.
https://gyucheolk.tistory.com/14
감사합니다~

**Comment by roeniss** [comment]
많이 늦었네요. 제출합니다.
https://velog.io/@roeniss/자바-기초지식-정리#8주차--인터페이스

**Comment by gintire** [comment]
8주차 과제 제출합니다~
https://gintrie.tistory.com/70

**Comment by HwangWonGyu** [comment]
인터페이스에 대해 공부해봤습니다.

3주차부터 꾸준히 토요일 밤10시 유튜브 라이브 참석하고 있습니다.
제 과제 제출 속도는 많이 더딘것 같네요😅

**중간후기**
우선 여러사람들이 깊게 공부한 내용을 종합해서 볼 수 있어서 유익하고 효율적인것 같습니다.
백기선님의 추가 설명까지 들을 수 있어서 무언가 얻어간다는 기대감에 공부 의지가 더 생기는것 같습니다. 
추천도서, 퀴즈, 재미있는 얘기, 인프런 쿠폰 등 편하고 재미있는 분위기라서 기분좋게 공부했던것 같습니다😃

https://www.notion.so/interface-b29f23d9a200426bb468fc7bf30607ad

**Comment by ehdrhelr** [comment]
8주차 과제 제출합니다!
https://www.notion.so/8-8-9b2e40cf5c1243d5b39cf3149374eb75

**Comment by dongyeon94** [comment]
8주차 과제입니다. 
지각이네요 ㅠ 죄송합니다.

https://dblog94.tistory.com/entry/Java-Study-8%EC%9D%BC%EC%B0%A8

**Comment by Jul-liet** [comment]
https://jul-liet.tistory.com/168

8주차과제 제출합니다 :)

**Comment by Park-Youngwoo** [comment]
https://www.notion.so/_8-2f0643cf6cec4f22ae72ba0a1531c51c
늦었지만 과제 제출합니다

**Comment by jikimee64** [comment]
https://dncjf64.tistory.com/262
과제 제출합니다!

**Comment by plzprayme** [comment]
[과제](https://velog.io/@prayme/whiteship-8%EC%A3%BC%EC%B0%A8-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4) 제출입니다

**Comment by highright96** [comment]
제출합니다!
https://github.com/highright96/java-study/blob/main/live-study/week8/week8.md

**Comment by awesomeo184** [comment]
8주차 과제 제출합니다.
https://wisdom-and-record.tistory.com/45

**Comment by oktopman** [comment]
8주차 과제 제출합니다~
https://github.com/oktopman/java-live-study/blob/main/assignment/week8.md#%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4%EC%9D%98-Default-Method-%EC%9E%90%EB%B0%94-8

**Comment by kwj1270** [comment]
드디어 거의 다 따라잡았네요 ㅠㅡㅠ   
앞으로도 뒤쳐지지 않고 더 힘껏 노를 저어 보겠습니다!    
[kwj1270 블로그-인터페이스](https://velog.io/@kwj1270/%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4)

**Comment by daroguzo** [comment]
8주차 과제입니다.
[https://github.com/daroguzo/JavaLiveStudy/blob/master/8.md](url)

**Comment by d-h-k** [comment]
8주차 과제입니다
https://www.notion.so/8-3e0f6fe6ba1e47f3a10d5ecea3a48c85
이번엔 늦었지만, 9주차에는 기필코! 반드시 on-time 하겠습니다

**Comment by pond1029** [comment]
https://velog.io/@pond1029/interface
과제 제출합니다

**Comment by chaejunlee** [comment]
과제 제출합니다!
https://www.notion.so/chaejunlee/8-d215eb6e968243b3b273c4c208481c8e

**Comment by JungHyeokMoon** [comment]
https://www.notion.so/8-dd17be1926e94e83b380a876a7b05cdc
8주차입니다.

**Comment by monkeyDugi** [comment]
https://www.notion.so/8-8a95317a4c7b44ef85a863fabc34f8be

**Comment by conyconydev** [comment]
8주차 과제 제출합니다!!
https://roeldowney.tistory.com/490

**Comment by JIN-096** [comment]
8주차 제출합니다!
[8주차](https://0x60.tistory.com/18)

**Comment by rowanlee92** [comment]
8주차 과제 제출합니다!
https://watrv41.gitbook.io/devbook/java/java-live-study/8_week

**Comment by morethanmin** [comment]
과제 제출하겠습니다.

https://moredevmin.tistory.com/16

**Comment by geneaky** [comment]
8주차 과제 제출합니다.!
https://www.notion.so/WEEK8-f4430d6cb69e418388bca879df952069

**Comment by joey3116** [comment]
8주차 과제 제출합니다. 

[8주차 과제](https://github.com/joey3116/live-study/blob/master/8week_assignment.md)

감사합니다.

**Comment by 372dev** [comment]
https://github.com/372dev/TIL/blob/main/JAVA/08_Interface_01.md
https://github.com/372dev/TIL/blob/main/JAVA/08_Interface_02.md
감사합니다

**Comment by ows3090** [comment]
8주차 과제 제출합니다.
https://math-coding.tistory.com/169

**Comment by ohjoohyung** [comment]
8주차 과제 제출합니다. 감사합니다~
https://ohcodingdiary.tistory.com/30

**Comment by hanull** [comment]
8주차 과제 제출합니다~ 항상 감사합니다!
https://github.com/hanull/java-live-study/blob/master/week8/note.md

**Comment by KwangJongJeon** [comment]
8주차 과제 제출합니다. 감사합니다
https://kj97.tistory.com/11

**Comment by HyangKeunChoi** [comment]
8주차 과제 늦은 제출입니다.ㅎ

https://geunyang93.tistory.com/44

**Comment by ejxzhn22** [comment]
https://sujin-k.tistory.com/73

**Comment by reumongshop** [comment]
8주차 과제 제출합니다 :)
https://blog.naver.com/reumongshop/222224209670

**Comment by haeinoh** [comment]
8주차 과제 제출합니다. 감사합니다.

https://void2017.tistory.com/184

**Comment by HyeonWuJeon** [comment]
8 주차과제 늦게나마 제출합니다. 항상 감사합니다.
https://www.notion.so/8-3bda456f9a414641b91b94797604350c

**Comment by lkimilhol** [comment]
8주차 과제 제출합니다.
https://github.com/lkimilhol/whiteship/blob/master/study/week08.md

**Comment by Ohzzi** [comment]
8주차 과제 제출합니다.
https://velog.io/@ohzzi/Live-Study-8

**Comment by Park-SooYeon** [comment]
8주차 과제 제출합니다.
https://github.com/Park-SooYeon/today-I-learned/blob/master/live-study/interface.md

**Comment by yskkkkkk** [comment]
8주차 과제입니다 
https://knowing-today.blogspot.com/2021/01/blog-post_8.html#more

**Comment by myBabyGrand** [comment]
[8주차 인터페이스](https://github.com/myBabyGrand/study_JAVA_whiteship_live-study/blob/main/md_doc/08.Interface.md)
way to go!!

**Comment by cmg1411** [comment]
[9주차 과제 제출합니다 !](https://alkhwa-113.tistory.com/entry/8%EC%A3%BC%EC%B0%A8-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4)

**Comment by takor88** [comment]
8주차 과제입니다.
https://delusidiot.tistory.com/entry/8-%EC%A3%BC%EC%B0%A8-%EA%B3%BC%EC%A0%9C-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4

**Comment by ventulus95** [comment]
8주차 과제 제출입니다~
https://www.notion.so/ventulus95/d3abfa444b754d818acc51167bd483ab

**Comment by delusidiot** [comment]
8주차 과제 제출합니다.
https://delusidiot.tistory.com/entry/8-%EC%A3%BC%EC%B0%A8-%EA%B3%BC%EC%A0%9C-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4

**Comment by eatnows** [comment]
https://eatnows.tistory.com/88
8주차입니다!

**Comment by loosie** [comment]
https://loosie.tistory.com/130?category=964815

8주차! 영차영차~

**Comment by devHTak** [comment]
8주차 과제 제출합니다.
https://devhtak.github.io/java%20study/2021/01/26/StudyHalle_Week08.html

**Comment by tinajeong** [comment]
8주차 과제 입니다~~~
https://velog.io/@maigumi/자바-인터페이스

**Comment by devvip** [comment]
8주차 과제 제출합니다!
https://velog.io/@eledev/JAVA-STUDYwith-whiteship-8주차-인터페이스

**Comment by loop-study** [comment]
8주차 과제입니다
https://loopstudy.tistory.com/15

**Comment by heewonham** [comment]
https://blog.naver.com/micky6414/222243441274

8주차 과제 제출합니다 ^,^

**Comment by Taein2** [comment]
8주차 제출입니다
https://codingrepo.tistory.com/37

**Comment by shinnyoung** [comment]
8주차 과제 제출 합니다.
https://parkbeaver.tistory.com/24

**Comment by Hwanse** [comment]
8주차 과제 제출합니다.

https://velog.io/@khsb2012/java-study-week8

**Comment by azurealstn** [comment]
https://github.com/azurealstn/TIL/blob/main/java/live-study/week-8.md
8주차 제출합니다~!

**Comment by olivejua** [comment]
https://olivejua-develop.tistory.com/54
8주차 과제 제출합니다.

**Comment by youngjinmo** [comment]
8주차 과제 제출합니다!
https://youngjinmo.github.io/2021/02/livestudy-week-08/

**Comment by star1606** [comment]
https://www.notion.so/8-dc7750bea7de48e7abdaecc31b915bcc
제출합니다

**Comment by jaeeunis** [comment]
https://github.com/jaeeunis/TIL/blob/main/Java/Interface.md
제출합니다!

**Comment by twowinsh87** [comment]
https://github.com/twowinsh87/twowinsh87.github.io/blob/master/_posts/Java/2021-02-04-week8.md

**Comment by yongtaelim** [comment]
8주차 제출합니다!!
https://jessyt.tistory.com/78

**Comment by choiyoungkwon12** [comment]
8주차 과제 제출합니다.
열심히 해서 다 끝내보도록 하겠습니다.
https://cyk0825.tistory.com/26

**Comment by YuSeungmo** [comment]
8주차 과제 제출합니다.
https://github.com/YuSeungmo/java_study/blob/main/study/8%EC%A3%BC%EC%B0%A8.md

**Comment by younwony** [comment]
8주차 과제 입니다!
https://youn12.tistory.com/31

**Comment by justinnn980** [comment]
https://justinnn980.tistory.com/16

**Comment by sophysophysophysophy** [comment]
https://read-write-developer.tistory.com/120
8주차 과제 제출합니다!

**Comment by hhlyn0328** [comment]
8주차 과제 입니다!
https://hongkey90.tistory.com/21

**Comment by soojpark91** [comment]
8주차 과제입니다.
https://soojpark.tistory.com/15

**Comment by rkdals213** [comment]
8주차 과제입니다.

https://www.notion.so/4189f65bde594913a90643a23345f1ca

**Comment by kdh9428** [comment]
8주차 과제 제출합니다!
https://www.notion.so/8-e6a3da98398946c7b879d6547436ace3

**Comment by BaeJi77** [comment]
https://baeji77.github.io/dev/java/java-study-08/

**Comment by HanJaehee** [comment]
8주차 과제 입니다.
https://hind-sight.tistory.com/manage/posts/

**Comment by jongyeans** [comment]
8주차 과제입니다. 
https://morebetterworld.tistory.com/16

**Comment by hanseo0109** [comment]
8주차 과제입니다.
https://velog.io/@hanseo0109/step8-Java-Interface

**Comment by sunnynote** [comment]
[8주차 과제](https://happyday3.tistory.com/78)입니다 감사합니다

**Comment by elon09** [comment]
https://www.notion.so/8-c906614208c8477eb8902c83325be75c
8주차 과제입니다!

**Comment by cs7998** [comment]
8주차 과제 제출합니다.
https://github.com/cs7998/live-study-java/blob/main/8.Interface.md

**Comment by haemanlee** [comment]
8주차 과제 제출합니다.

https://haemanlee.tistory.com/19
