### ISSUE TITLE
9주차 과제: 예외 처리

### ISSUE THREAD

**Issue by whiteship** [whiteship/live-study#9]
# 목표
자바의 예외 처리에 대해 학습하세요.

# 학습할 것 (필수)
* 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)
* 자바가 제공하는 예외 계층 구조
* Exception과 Error의 차이는?
* RuntimeException과 RE가 아닌 것의 차이는?
* 커스텀한 예외 만드는 방법

# 마감일시
2021년 1월 16일 토요일 오후 1시까지.

**Comment by Jason-time** [comment]
https://github.com/Jason-time/java_study_with_whiteship/blob/main/mds/week08.md

8주차 과제 주소입니다.

**Comment by awesomeo184** [comment]
9주차 과제 제출합니다.
https://wisdom-and-record.tistory.com/46

**Comment by sujl95** [comment]
9주차 과제입니다
https://sujl95.tistory.com/62

**Comment by Lob-dev** [comment]
https://lob-dev.tistory.com/entry/Live-StudyWeek-09-예외-처리

9주차 과제 제출합니다!

**Comment by hojunnnnn** [comment]
9주차 과제 제출합니다.
https://dev-coco.tistory.com/18
감사합니다.!

**Comment by lee-maru** [comment]
9주차 과제입니다. 스터디하는 선원 분들 백선생님 모두 화이팅입니다.

https://catch-me-java.tistory.com/46

**Comment by ssonsh** [comment]
9주차 과제 제출합니다. :-D
https://www.notion.so/3565a9689f714638af34125cbb8abbe8

**Comment by rlatmd0829** [comment]
https://wookcode.tistory.com/21

9주차 과제제출합니다!

**Comment by mongzza** [comment]
[9주차 과제](https://github.com/mongzza/java-study/blob/main/study/9%EC%A3%BC%EC%B0%A8.md) 제출합니다. 감사합니다~

**Comment by ddings73** [comment]
[9주차과제](https://ddings73.github.io/Category/Java/week09.html) 제출합니다.  
 감사합니다!

**Comment by highright96** [comment]
제출합니다!
https://github.com/highright96/java-study/blob/main/live-study/week9/week9.md

**Comment by LeeGiCheol** [comment]
9주차 과제 제출합니다~~
감사합니다!

https://leegicheol.github.io/whiteship-live-study/whiteship-live-study-09-exception-handling/

**Comment by kongduboo** [comment]
[9주차 과제: 예외 처리](https://github.com/kongduboo/whiteship-java-study/blob/main/week9.md) 제출합니다.
감사합니다~

**Comment by clap1030** [comment]
9주차 과제 제출합니다. 감사합니다.

https://i-am-clap.tistory.com/12

**Comment by SeungWoo-Oh** [comment]
9주차 과제 제출합니다.
[https://blog.naver.com/swoh1227/222203699618](https://blog.naver.com/swoh1227/222203699618)

**Comment by jongnan** [comment]
9주차 과제 입니다~
* [예외 처리](https://github.com/jongnan/Java_Study_With_Whiteship/blob/master/week9/week9.md)

**Comment by hyeonic** [comment]
9주차 과제 제출입니다!
https://hyeonic.tistory.com/57

**Comment by Youngerjesus** [comment]
9주차 과제 제출합니다

https://velog.io/@youngerjesus/%EC%9E%90%EB%B0%94-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC

**Comment by rkdals213** [comment]
9주차 과제 제출입니다
https://www.notion.so/cce3fc21976f4400aa4ed8d3fb26497b

**Comment by SJParkkk** [comment]
9주차 과제 제출합니다.
https://sjparkk.tistory.com/11

**Comment by sejongdeveloper** [comment]
선장님 9주차 과제 제출합니다!
https://blog.naver.com/sejonghumble/222206512410

**Comment by yangseungin** [comment]
과제 제출합니다.
https://giantdwarf.tistory.com/49

**Comment by sungpillhong** [comment]
9주차 과제 제출합니다. 

https://github.com/sungpillhong/whiteshipstudy/blob/master/9%EC%A3%BC%EC%B0%A8.md

**Comment by JadenKim940105** [comment]
9주차 과제입니다 :) 
https://velog.io/@jaden_94/9주차-항해일지

**Comment by sangwoobae** [comment]
https://blog.baesangwoo.dev/posts/java-livestudy-9week/
9주차 과제 제출합니다.
이번 과제는 글이 좀 길어졌네요 ㅠㅠ

**Comment by kjw217** [comment]
9주차 과제입니다.
https://github.com/kjw217/whiteship-live-study/blob/master/9th-week/9th-week.md

**Comment by Chohongjae** [comment]
https://chohongjae.github.io/livestudy/live-study-week9/
9주차 과제입니다.

**Comment by KJJ924** [comment]
9주차 과제

https://k3068.tistory.com/41

**Comment by Junhan0037** [comment]
9주차 과제입니다.

https://www.notion.so/9-ad6b0f325de64bbdadabe19d1cdde021

**Comment by soongjamm** [comment]
9주차 과제입니다~
https://soongjamm.tistory.com/124

**Comment by ZhenxiKim** [comment]
9주차 과제 제출합니다!
https://zhenxikim.tistory.com/27

**Comment by UmJaeJeong** [comment]
9주차 예외처리 과제 제출합니다!!!
https://blog.naver.com/umjaejeong2/222207563947

**Comment by etff** [comment]
9주차 과제 제출합니다.
https://itcoin.tistory.com/494

**Comment by asqwklop12** [comment]
https://b-programmer.tistory.com/manage/newpost/?type=post&returnURL=%2Fmanage%2Fposts%2F 
이글을 준비하면서 커스텀 예외는 반드시 필요한가에 대해 고민하게 되더라 구요. 상황에 맞게 사용하는게 best라고 생각하는데,
솔직히 그 best가 뭔지 잘 모르겠습니다. ;;

**Comment by garlickim** [comment]
9주차 과제 제출합니다.
[https://github.com/garlickim/whiteship-live-java-study/week9](https://github.com/garlickim/whiteship-live-java-study/blob/main/%5Bweek9%5D%20%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC.md)

**Comment by ChoiGiSung** [comment]
https://github.com/ChoiGiSung/JavaStudy/blob/main/9%EC%A3%BC%EC%B0%A8.md
이번에도 많이 배워갑니다!~

**Comment by giyeon95** [comment]
9주차 과제 제출합니다.

https://giyeon95.github.io/whiteship/whiteship_study_week09/

감사합니다~!

**Comment by kyu9** [comment]
9주차 과제입니다.
https://github.com/kyu9/WS_study/blob/master/week9.md
좋은 공부하게 만들어주셔서 항상 감사드립니다!

**Comment by Yadon079** [comment]
9주차 제출합니다 :3
https://yadon079.github.io/2021/java%20study%20halle/week-09

**Comment by 2yeseul** [comment]
[9주차 과제 제출합니다.](https://www.notion.so/2yeseul/9-640e27bdb3f84c959bae4b80181430c5)

**Comment by Resilient923** [comment]
9주차 과제 제출합니다!
https://resilient-923.tistory.com/117

**Comment by DevelopJKong** [comment]
9주차 과제 제출합니다!! 항상 감사합니다!
https://blog.naver.com/tbaram10/222205933141

**Comment by limyeonsoo** [comment]
9주차 과제 제출합니다. 아리송하고 헷갈리는 한 주 였습니다. 
감사합니다!
https://www.notion.so/9-c040e3ace4994bb49b1bc54953e6a62a

**Comment by minikuma** [comment]
9주차 과제 제출합니다. 감사합니다. : )
https://www.notion.so/9-17a778bba6ed4436ac3d7b9415b6babb

**Comment by jjone36** [comment]
9주차 과제 제출합니다
https://github.com/jjone36/self-study/blob/main/java_live_study/week09.md

**Comment by GetMapping** [comment]
9주차 과제 제출합니다!
https://www.notion.so/9-cc05b43184f9459daabb56bcba4db279

**Comment by hoi-hoon** [comment]
9주차 과제 제출합니다~!
https://hoi-hoon.github.io/study/live-study-9/

**Comment by yhh1056** [comment]
9주차 과제 제출합니다~
여태 Unchecked Exception과 Checked Exception를 모르고 사용하고 있던 자신을 발견한 한 주였습니다.
감사합니다.
(https://www.notion.so/63215ca7e439406c93a2b40d9b565acb)

**Comment by Azderica** [comment]
9주차 과제제출합니다.
https://azderica.github.io/09-java-study

**Comment by pka0220z** [comment]
https://out-of-memory.tistory.com/14
9주차 과제 제출합니다~ 감사합니다

**Comment by damho1104** [comment]
https://www.notion.so/damho1104/9-ea925b37b3274e1da106ed82162f8c84
9주차 스터디 정리본 입니다.

**Comment by ksundong** [comment]
https://velog.io/@dion/백기선님-온라인-스터디-9주차-예외-처리
9주차 과제 제출합니다!

**Comment by good-influence** [comment]
9주차 과제 제출합니다,
https://www.notion.so/9-Exception-handling-2dd3692a5b7b48d49b57de1be9649131

감사합니다.

**Comment by minzzang** [comment]
9주차 제출합니다 ~
https://minzzang.tistory.com/11

**Comment by SooJungDev** [comment]
[9주차과제](https://github.com/SooJungDev/TIL/blob/master/Java/live-study/9%EC%A3%BC%EC%B0%A8%EA%B3%BC%EC%A0%9C.md) 제출합니다! 감사합니다

**Comment by castleCircle** [comment]
https://castleone.tistory.com/12 과제제출합니다.

**Comment by rockintuna** [comment]
안녕하세요. 9주차 과제입니다.
https://rockintuna.tistory.com/84

**Comment by MoonHKLee** [comment]
https://leemoono.tistory.com/24

**Comment by KyungJae-Jang** [comment]
9주차 과제 제출합니다.
감사합니다.
https://www.notion.so/9-b9c1cfc9d060463381bbbe52615faafb

**Comment by DDOEUN** [comment]
9주차 과제 제출합니다.
감사합니다!
https://teamo-oeun.tistory.com/16?category=861194

**Comment by nimkoes** [comment]
9주차 과제 입니다.
https://blog.naver.com/hsm622/222208809905

**Comment by haemin-jeong** [comment]
9주차 과제 제출합니다 감사합니다!!
https://developer-hm.tistory.com/31

**Comment by gtpe** [comment]
9주차 과제입니다! 감사합니다(__)
https://github.com/gtpe/java-study/blob/master/w9.md

**Comment by jymaeng95** [comment]
9주차 과제 제출합니다! 감사합니다!
https://velog.io/@zayson/백기선님과-함께하는-Live-Study-9주차-예외-처리

**Comment by gcha-kim** [comment]
9주차 과제 제출합니다.
https://www.notion.so/gcha/9-Week-ff52148912414e0d8d93adea3057d8ba

**Comment by bingbingpa** [comment]
9주차 과제 제출합니다.
https://bingbingpa.github.io/java/whiteship-live-study-week9/

**Comment by parksil0** [comment]
9주차 과제 제출합니다. 감사합니다!
https://github.com/parksil0/live-study/blob/master/09th.week.md

**Comment by ysmiler** [comment]
[9주차](https://ysmiler.github.io/study/java/live-study/week9/)

과제 제출합니다. 덕분에 많이 배웁니다. 감사합니다!!

**Comment by iseunghan** [comment]
9주차 과제 제출합니다~ 
https://iseunghan.tistory.com/271?category=912560

**Comment by dongyeon94** [comment]
9주차 과제 제출합니다. 남은기간 힘내보겠습니다.

https://dblog94.tistory.com/entry/Java-Study-9%EC%9D%BC%EC%B0%A8

**Comment by dacapolife87** [comment]
9주차 과제 제출합니다.
https://github.com/dacapolife87/javaStudy/blob/main/study/week09/Week09_exception.md

**Comment by doyoung0205** [comment]
9주차 과제 제출합니다.
https://doyoung.tistory.com/22

**Comment by integer87** [comment]
9주차 과제 제출합니다.
https://github.com/integer87/study/blob/master/chapter9/chapter9.md

**Comment by Gomding** [comment]
9주차 과제 제출합니다.
https://parkadd.tistory.com/47

예외에 대한 더 명확한 개념을 잡을 수 있어서 좋았습니다!
감사합니다.

**Comment by resister12** [comment]
9주차 과제 제출합니다.
https://www.notion.so/9-a09130bda8564b168ef1857a8d6ee9cc

**Comment by hiYoungSeop** [comment]
9주차 과제 제출합니다. 감사합니다 :)
https://www.notion.so/9-a1ca6f376c8640cfacdc60c6ae6da4f0

**Comment by yky03** [comment]
https://github.com/yky03/java-study-issues/blob/main/week9-exception.md

**Comment by pej4303** [comment]
9주차 과제 제출합니다:)
https://pej4303.tistory.com/59

**Comment by jameshan521** [comment]
9주차 과제 제출합니다! 
https://imdigging.tistory.com/6

**Comment by ByungJun25** [comment]
9주차 과제 제출합니다. 
감사합니다.
https://github.com/ByungJun25/study/tree/main/java/whiteship-study/9week

**Comment by pond1029** [comment]
https://velog.io/@pond1029/exception
과제 제출합니다

**Comment by LeeJeongSeok** [comment]
과제 제출합니다.
https://velog.io/@ljs0429777/9주차-과제-예외-처리
throws 할 때 던지고 던지다 보면 결국 main 메소드에서 마지막으로 처리를 해야 하는 걸로 알고 있는데 여기서도 던지면 jvm에서 처리한다는 내용을 본 거 같은데 구체적으로 어떤 식으로 처리가 되는지 여쭤봐도 될까요?

**Comment by 9m1i9n1** [comment]
[9주차 과제](https://github.com/9m1i9n1/TIL_Today-I-Learned/blob/master/05_Java/03_liveStudy/09_%EC%98%88%EC%99%B8%20%EC%B2%98%EB%A6%AC.md)

과제제출합니다! 감사합니다~

**Comment by keunyop** [comment]
https://github.com/keunyop/java-study-with-whiteship/blob/main/live-study/week9.md

감사합니다.

**Comment by Jangilkyu** [comment]
과제 제출합니다.!
https://github.com/Jangilkyu/Java_Study/tree/main/Week9

**Comment by tocgic** [comment]
과제 제출 드립니다.
https://github.com/tocgic/study-java-basic/blob/develop/week9.md

감사합니다.

**Comment by githubjam2** [comment]
9주차 과제 제출입니다

https://blog.naver.com/shpain2/222206744796

**Comment by Sungjun-HQ** [comment]
https://whereishq.blogspot.com/2021/01/9.html

항상 감사합니다~

**Comment by CODEMCD** [comment]
안녕하세요!
9 주차 과제 제출하겠습니다.
[9 주차 과제 링크](https://www.notion.so/9-fb843df7bc4040adbe26799dabd0e6e9)

감사합니다!

**Comment by chulphan** [comment]
안녕하세요

9주차 과제 제출합니다

감사합니다
https://chulphan.tistory.com/12

**Comment by zhaoSeo** [comment]
9주차 과제 제출합니다
https://zhaogo.tistory.com/24

**Comment by numuduwer** [comment]
9주차 과제 제출합니다.
https://www.notion.so/9-dd3acffc8819478293d740ab0ff3b072

**Comment by devShLee7017** [comment]
9주차 과제 제출합니다.
https://velog.io/@bluesky7017/%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC

**Comment by 1031nice** [comment]
9주차 과제입니다. 감사합니다!
https://github.com/1031nice/JavaStudy/blob/master/live-study/week9.md

**Comment by honux77** [comment]
[9주차 과제](https://velog.io/@honux/%EB%B0%B1%EA%B8%B0%EC%84%A0-%EC%9E%90%EB%B0%94-%EB%9D%BC%EC%9D%B4%EB%B8%8C-%EC%8A%A4%ED%84%B0%EB%94%94-9-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC)

마감 직전이네요.  열심히 항해를 하고 있으니 뭔가 루피와 선원들 같군요 ㅋㅋ. 우리 모두 라프텔에 가서 원피스를 찾아요!

**Comment by hongminpark** [comment]
9주차 과제 제출합니다 :) https://hongminpark.github.io/2021-01-16/studyhalle09

**Comment by BaeJi77** [comment]
과제 제출입니다.
https://baeji77.github.io/dev/java/java-study-09/

**Comment by redbean88** [comment]
9주차 과제 입니다. 감사합니다.
https://github.com/redbean88/redbean88.github.io/blob/master/_posts/2021-01-14-whiteship-study-9week.md

**Comment by HyangKeunChoi** [comment]
9주차 입니당
https://geunyang93.tistory.com/45

**Comment by JeongJin984** [comment]
9주차 과제입니다: https://github.com/JeongJin984/JeongJin984.github.io/blob/master/_posts/2021-01-16-Java-Exception.md

**Comment by rshak8912** [comment]
9주차 과제 제출합니다.
[9주차 과제](https://java-boy.tistory.com/100)

**Comment by jiwoo-choi** [comment]
https://www.notion.so/9-3da9f8beff8a440398f906704b816da4
9주차 과제입니다.

**Comment by yeGenieee** [comment]
9주차 과제 제출합니다 ~

**Comment by Myeongkook** [comment]
9주차 과제입니다
https://cookie92.tistory.com/18

**Comment by sinchang1** [comment]
30분만에 하느라 좀 어설픕니다.ㅠㅠ 시간날때 보강하려합니다.
https://www.notion.so/Week_9-Baik-s-JAVA_STUDY-28c6cbcd5c2b4403a39061e9ed3daae0

**Comment by sjinjin7** [comment]
9주차 과제입니다
https://kimvampa.tistory.com/128

**Comment by whiteship** [comment]
마감 시간이 지나서 이슈는 닫지만 계속 제출하실 수 있습니다.

**Comment by GetMapping** [comment]
9주차 과제 제출합니다.
https://www.notion.so/9-cc05b43184f9459daabb56bcba4db279

**Comment by Jason-time** [comment]
https://github.com/Jason-time/java_study_with_whiteship/blob/main/mds/week09.md
아름다운 겨울입니다. ~
9주차 과제입니다.~

**Comment by sskim91** [comment]
9주차 과제입니다.
https://amagrammer91.tistory.com/52

**Comment by KilJaeeun** [comment]
지각입니다~
https://kils-log-of-develop.tistory.com/476#throws

**Comment by abcdsds** [comment]
9주차 제출합니다.
https://www.notion.so/9-e34172c945ae40e798591753f8e3ca48

**Comment by jeeneee** [comment]
지각했네요ㅠ 9주차 과제 제출합니다~
https://jeeneee.dev/java-live-study/week9-exception-handling/

**Comment by haemanlee** [comment]
9주차 과제 제출합니다!

https://haemanlee.tistory.com/7

**Comment by HwangWonGyu** [comment]
예외에 대해서 공부했습니다

https://www.notion.so/Exception-9c674eeb2ca849fd8c0542a428719290

**Comment by HyangKeunChoi** [comment]
9주차 과제 다시 제출 드립니다. ㅠㅠ
https://geunyang93.tistory.com/45

**Comment by LeeWoooo** [comment]
9주차 제출입니다!
https://github.com/LeeWoooo/Java_LiveStudy/tree/master/week9

**Comment by roeniss** [comment]
https://velog.io/@roeniss/자바-기초지식-정리#9주차--예외처리

**Comment by plzprayme** [comment]
[9주차 과제 제출입니다](https://velog.io/@prayme/whiteship-9%EC%A3%BC%EC%B0%A8-%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC)

**Comment by thisisyoungbin** [comment]
https://young-bin.tistory.com/75
9주차 예외처리 과제입니다.

**Comment by jikimee64** [comment]
https://dncjf64.tistory.com/271
과제 제출 합니다!!

**Comment by oktopman** [comment]
과제 제출합니다~
https://github.com/oktopman/java-live-study/blob/main/assignment/week9.md

**Comment by JungHyeokMoon** [comment]
https://www.notion.so/9-7290d2d06efd43aa8951aa37a8b230f3

9주차과제입니다.

**Comment by kingsubin** [comment]
https://kingsubin.tistory.com/337

**Comment by kgc0120** [comment]
과제 제출합니다~
https://gyucheolk.tistory.com/16
감사합니다

**Comment by kwj1270** [comment]
9주차 과제 제출입니다.
조금 늦었지만, 라이브 강의로 새롭게 배운 지식들이 많아서 너무 즐겁고,
이 내용들을 추가해서 지속적으로 업데이트 하겠습니다.     
[kw1270의 블로그](https://velog.io/@kwj1270/%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC)

**Comment by plzprayme** [comment]
[과제 제출입니다](https://velog.io/@prayme/whiteship-9%EC%A3%BC%EC%B0%A8-%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC)

**Comment by ohsg0226** [comment]
https://ohsg0226.tistory.com/3
과제제출입니다

**Comment by WonYong-Jang** [comment]
과제 제출합니다.
[https://wonyong-jang.github.io/java/2021/01/14/Java-Exception-Handling.html](https://wonyong-jang.github.io/java/2021/01/14/Java-Exception-Handling.html)

**Comment by daroguzo** [comment]
9주차 과제 제출합니다.
[https://github.com/daroguzo/JavaLiveStudy/blob/master/9.md](url)

**Comment by ShimSeoungChul** [comment]
9주차 과제 제출합니다!
https://scshim.tistory.com/238

**Comment by Ahnyezi** [comment]
9주차 과제 제출합니다!
- [과제 : 예외처리](https://ahnyezi.github.io/java/javastudy-9-exception/)

**Comment by jongyeans** [comment]
9주차 과제 제출합니다. 
https://morebetterworld.tistory.com/10?category=934047

**Comment by morethanmin** [comment]
9주차 제출하겠습니다.

https://moredevmin.tistory.com/18

**Comment by JIN-096** [comment]
9주차 제출하겠습니다.
[9주차](https://0x60.tistory.com/19)

**Comment by joey3116** [comment]
9주차 과제 제출합니다.

[예외처리](https://github.com/joey3116/live-study/blob/master/9week_assignment.md)

**Comment by conyconydev** [comment]
9주차 제출합니다. 
https://roeldowney.tistory.com/492

**Comment by monkeyDugi** [comment]
https://www.notion.so/9-f471cba84ef54c66a9c98b9532846083

**Comment by geneaky** [comment]
9주차 과제 제출합니다.
https://www.notion.so/WEEK9-c164465c8cf94f8aa541144b7b69ca83

**Comment by chaejunlee** [comment]
https://www.notion.so/chaejunlee/9-7c36cae3a64d45b09ca271bed80b2b74
9주차 과제 제출합니다!

**Comment by ohhhmycode** [comment]
https://ohhhmycode.tistory.com/13

늦었지만 제출합니다!

**Comment by chlaudeh** [comment]
https://blog.naver.com/chlaudeh/222218887940
9주차 공부입니다

**Comment by rowanlee92** [comment]
9주차 과제 제출합니다!
https://watrv41.gitbook.io/devbook/java/java-live-study/9_week

**Comment by Park-Youngwoo** [comment]
https://www.notion.so/_9-acf13e3f399340a08a378e3e22eb9fb1
늦게나마 제출합니다.

**Comment by ohjoohyung** [comment]
9주차 과제 제출합니다! 감사합니다~
https://ohcodingdiary.tistory.com/31

**Comment by heonjun91** [comment]
9주차 과제 제출합니다.
https://github.com/heonjun91/javalivestudy/blob/master/src/main/java/com/javalivestudy/assignment9/assignment9.md

**Comment by reumongshop** [comment]
9주차 과제 제출합니다 :)
https://blog.naver.com/reumongshop/222224316451

**Comment by ejxzhn22** [comment]
https://sujin-k.tistory.com/75

**Comment by KwangJongJeon** [comment]
9주차 과제 제출합니다
https://kj97.tistory.com/13

**Comment by ows3090** [comment]
9주차 과제 제출합니다
https://math-coding.tistory.com/170

**Comment by devHTak** [comment]
9주차 과제 제출합니다.
https://devhtak.github.io/java%20study/2021/02/01/StudyHalle_Week09.html

**Comment by lkimilhol** [comment]
9주차 과제 제출합니다.

https://github.com/lkimilhol/whiteship/blob/master/study/week09.md

**Comment by Park-SooYeon** [comment]
9주차 과제 제출합니다.
https://github.com/Park-SooYeon/today-I-learned/blob/master/live-study/exception-handling.md

**Comment by cmg1411** [comment]
[9주차 과제 제출합니다!](https://alkhwa-113.tistory.com/entry/9%EC%A3%BC%EC%B0%A8-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC)

**Comment by Ohzzi** [comment]
9주차 과제 제출합니다
https://velog.io/@ohzzi/Live-Study-9

**Comment by takor88** [comment]
9주차 과제 제출합니다.
https://delusidiot.tistory.com/entry/9-%EC%A3%BC%EC%B0%A8-%EA%B3%BC%EC%A0%9C-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC

**Comment by delusidiot** [comment]
9주차 과제 제출합니다.
https://delusidiot.tistory.com/entry/9-%EC%A3%BC%EC%B0%A8-%EA%B3%BC%EC%A0%9C-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC

**Comment by haeinoh** [comment]
9주차 과제 제출합니다. 감사합니다.

https://void2017.tistory.com/190

**Comment by myBabyGrand** [comment]
[9주차](https://github.com/myBabyGrand/study_JAVA_whiteship_live-study/blob/main/md_doc/09.Exception.md) 제출합니다
way to go!

**Comment by loosie** [comment]
https://loosie.tistory.com/131

9주차 영차영차!
그냥 생각없이 쓰다가 이렇게 직접적으로 예외처리를 다뤄보니 새롭네요...

**Comment by cocodori** [comment]
https://coco-log.tistory.com/135

9주차 과제 Exception입니다.

**Comment by ventulus95** [comment]
9주차 과제입니다
https://www.notion.so/ventulus95/b95cf3d0849f4eaba0b4b2a3c0eb9099

**Comment by jigmini** [comment]
https://blog.naver.com/jigmini/222240260781

**Comment by eatnows** [comment]
https://eatnows.tistory.com/89
9주차입니다!

**Comment by loop-study** [comment]
https://loopstudy.tistory.com/16
9주차 과제입니다!

**Comment by Taein2** [comment]
9주차 제출입니다!
https://codingrepo.tistory.com/38

**Comment by heewonham** [comment]
https://blog.naver.com/micky6414/222243636023

9주차 제출합니다 ^,^

**Comment by devvip** [comment]
9주차 과제 제출합니다.
https://velog.io/@eledev/JAVA-STUDYwith-whiteship-9주차-예외-처리

**Comment by shinnyoung** [comment]
9주차 과제 제출합니다.
https://parkbeaver.tistory.com/25

**Comment by tinajeong** [comment]
9주차 과제입니다!!
https://velog.io/@maigumi/예외-처리

**Comment by azurealstn** [comment]
https://github.com/azurealstn/TIL/blob/main/java/live-study/week-9.md
9주차 제출합니다~

**Comment by Hwanse** [comment]
9주차 과제입니다.

https://velog.io/@khsb2012/java-study-week9

**Comment by yskkkkkk** [comment]
9주차 과제 제출하겠습니다~ 

https://knowing-today.blogspot.com/2021/01/9.html#more

**Comment by jaeeunis** [comment]
https://github.com/jaeeunis/TIL/blob/main/Java/Exception.md
제출합니다!

**Comment by HyeonWuJeon** [comment]
https://notion.hyeonwoo.ml/5869450c-9d00-4ecb-b2e6-09565e5bcdf6
9주차입니다

**Comment by choiyoungkwon12** [comment]
9주차 과제 제출 합니다.
https://cyk0825.tistory.com/manage/posts/

**Comment by yongtaelim** [comment]
제출합니다!!
https://jessyt.tistory.com/79

**Comment by younwony** [comment]
9주차 과제입니다!
https://youn12.tistory.com/32

**Comment by hhlyn0328** [comment]
9주차 과제입니다!
https://hongkey90.tistory.com/22

**Comment by youngjinmo** [comment]
9주차 과제입니다!!
https://youngjinmo.github.io/2021/02/livestudy-week-09/

**Comment by justinnn980** [comment]
9주차 과제 입니다.
https://justinnn980.tistory.com/manage/posts/

**Comment by sophysophysophysophy** [comment]
https://read-write-developer.tistory.com/121
9주차 과제 제출합니다.

**Comment by s0w0s** [comment]
https://www.notion.so/9-30ab82d0b7904486bde567831a56ced6
9주차 과제 제출합니다.

**Comment by RealSong88** [comment]
9주차 과제입니다.

https://www.notion.so/9-244fe185f21947bab335a7075c12f5c0

**Comment by 372dev** [comment]
아자잣!

https://github.com/372dev/TIL/blob/main/JAVA/09_Exception_01.md
https://github.com/372dev/TIL/blob/main/JAVA/09_Exception_02.md

**Comment by JJongSue** [comment]
9주차 과제입니다.
https://github.com/JJongSue/javastudy/tree/master/src/main/java/week9

**Comment by inhalin** [comment]
9주차 과제 제출합니다. 아직 못한 부분은 이번주 내에 보충하겠습니다.

https://github.com/inhalin/whiteship-live-study/blob/main/week09.md

**Comment by hanseo0109** [comment]
9주차 과제 제출합니다.
https://velog.io/@hanseo0109/step9-Java-Exception

**Comment by YuSeungmo** [comment]
9주차 과제 제출합니다.
https://github.com/YuSeungmo/java_study/blob/main/study/9%EC%A3%BC%EC%B0%A8.md

**Comment by kdh9428** [comment]
9주차 과제 제출합니다!
https://www.notion.so/9-477cc85292a74471aa68478769a3be18

**Comment by cs7998** [comment]
9주차 과제 제출합니다.
https://github.com/cs7998/live-study-java/blob/main/9.Exception.md

**Comment by sunnynote** [comment]
[9주차 과제](https://happyday3.tistory.com/79) 제출합니다! 감사합니다
